# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

export no_proxy="localhost,127.0.0.0/8"
export HOME="/home/idea/"

#NIKIRA related Variables
#-------------------------
export CC='gcc -m64'
export LDFLAGS="-m64 -L$FLEXINSTALLDIR/lib -L${LIBICONVDIR}/lib -L$OPENSSLDIR/lib/ -L${GCC_HOME}/lib/${OS_TYPE} -L${GCC_HOME}/lib -O2 -pthread"
export CFLAGS="-m64 -I${GCC_HOME}/include -I${LIBICONVDIR}/include -I${OPENSSLDIR}/include -O2 -pthread"
export CXXFLAGS=$CFLAGS
export CPPFLAGS=$CFLAGS
export OSCFLAGS=$CFLAGS

export  PATH=$PATH
export  JAVA_HOME=/

#Nikira Tools
export  PATH=$JAVA_HOME:$PATH
export  LD_LIBRARY_PATH=$JAVA_HOME
export  ANTLRDIR=/home/NikiraServerTools/ANTLR
export  LIBICONVDIR=/home/NikiraServerTools/LIBICONV
export  LIBICONV_PATH=/home/NikiraServerTools/LIBICONV
export  BOOSTINSTALLDIR=/home/NikiraServerTools/BOOST
export  DAMEINSTALLDIR=/home/NikiraServerTools/DAME
export  FLEXINSTALLDIR=/home/NikiraServerTools/FLEX
export  BISONINSTALLDIR=/home/NikiraServerTools/BISON
export  BITMAPINSTALLDIR=/home/NikiraServerTools/BITMAP
export  AUTOCODEDIR=/home/NikiraServerTools/AUTOCODE
export  XMLRPCINSTALLDIR=/home/NikiraServerTools/XMLRPC
export  JUDYINSTALLDIR=/home/NikiraServerTools/JUDY
export  YAJLINSTALLDIR=/home/NikiraServerTools/YAJL
export  CURLINSTALLDIR=/home/NikiraServerTools/CURL
export  RUBYROOT=/home/NikiraClientTools/RUBYROOT
export  CMAKEINSTALLDIR=/home/NikiraServerTools/CMAKE_301
export  OPENSSLDIR=/home/NikiraServerTools/OPENSSL
export  RUBYINSTALLDIR=/home/NikiraClientTools/RUBYROOT

#Oracle
export  ORACLE_HOME=/home/oracle/app/oracle/product/11.2.0/dbhome_1
export  ORACLE_SID=orcl
export  CLASSPATH=$ORACLE_HOME/JRE:$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib
export  CLASSPATH=$ANTLRDIR/share/antlr-2.7.2/antlrall.jar

export TWO_TASK=$ORACLE_SID
export DB_USER=ideadev
export DB_PASSWORD=ideadev
export SPARK_DB_USER=idea_spark
export SPARK_DB_PASSWORD=idea_spark
export SQL_COMMAND="sqlplus"

export DASHBOARD_DB_USER=idea_dashboard
export DASHBOARD_DB_PASSWORD=idea_dashboard

export DB_HOSTNAME=10.113.58.198
export IP_ADDRESS=10.113.58.198

export ENCRYPTED_DB_USER=20f5b5fae98a8c6b3f41cf0b1b3a9e3e
export ENCRYPTED_PASSWORD=20f5b5fae98a8c6b3f41cf0b1b3a9e3e


# NIKIRA

export DBSETUP_CHECKOUT_PATH="/home/idea/ROCFraudManagement-7.4.2/DBSetup"
export SERVER_CHECKOUT_PATH="/home/idea/ROCFraudManagement-7.4.2/Server"


export RANGERHOME="/home/idea/FMSROOT"
export PREVEAHOME=$RANGERHOME
export WEBSERVER_RANGER_HOME=$RANGERHOME
export RANGERROOT=$RANGERHOME
export NIKIRAROOT=$RANGERHOME
export NIKIRACLIENT="/home/idea/ROCFraudManagement-7.4.2/Client/src"
export NIKIRA32BITLIB=$RANGERHOME/lib

export SQL_COMMAND="sqlplus"

export  PATH=$BISONINSTALLDIR/bin:$LIBICONVDIR/include:$LIBICONVDIR/bin:/usr/lib64/ccache:$DAMEINSTALLDIR/bin:$DAMEINSTALLDIR/include:$ANTLRDIR/bin:$JAVA_HOME/bin:$FLEXINSTALLDIR/include:$FLEXINSTALLDIR/bin:$BITMAPINSTALLDIR/bin:$BITMAPINSTALLDIR/include:$XMLRPCINSTALLDIR/include:$JUDYINSTALLDIR/include:$CURLINSTALLDIR/bin:$CURLINSTALLDIR/include:$RUBYROOT/bin:/home/oracle/app/oracle/product/11.2.0/dbhome_1/bin:.:$BOOSTINSTALLDIR/include:$CMAKEINSTALLDIR/bin:$AUTOCODEDIR/bin:$YAJLINSTALLDIR/bin:$YAJLINSTALLDIR/include:$RANGERHOME/sbin:/usr/local/include/:$RANGERHOME/bin:$PATH

export  LD_LIBRARY_PATH=/home/NikiraServerTools/OPENSSL/lib/:$BISONINSTALLDIR/lib:$LIBICONVDIR/lib:$ANTLRDIR/lib:$JAVA_HOME/lib:$FLEXINSTALLDIR/lib:$BITMAPINSTALLDIR/lib:$XMLRPCINSTALLDIR/lib:$JUDYINSTALLDIR/lib:$CURLINSTALLDIR/lib:$RUBYROOT/lib:$ORACLE_HOME/lib:/lib:$BOOSTINSTALLDIR/lib:$CMAKEINSTALLDIR/lib:$YAJLINSTALLDIR/lib:$OPENSSLDIR/lib:/usr/local/lib:/usr/lib64/:/home/idea/FMSROOT/lib:.

export RUBYLIB=$RUBYINSTALLDIR/lib/ruby/gems/1.8/gems/soap4r-1.5.8/lib/:$RUBYINSTALLDIR/lib/ruby:$RUBYINSTALLDIR/lib/ruby/1.8:$RUBYINSTALLDIR/lib/ruby/1.8/:$RUBYINSTALLDIR/lib/ruby/site_ruby/1.8:$RUBYINSTALLDIR/lib/ruby/site_ruby/1.8/:$RUBYINSTALLDIR/lib/ruby/gems/1.8/gems:$RUBYINSTALLDIR/lib/ruby/gems/1.8/gems/net-ssh-2.0.1/lib:$RUBYINSTALLDIR/lib/ruby/gems/1.8/gems/needle-1.3.0/lib:$RUBYINSTALLDIR/lib/ruby/gems/1.8/gems/soap4r-1.5.8/lib:$RUBYINSTALLDIR/lib/ruby/gems/1.8/gems/soap4r-1.5.8/lib/:$RUBYINSTALLDIR/lib/ruby/gems/1.8/gems/net-sftp-2.0.1/lib:.

# User specific aliases and functions
export vi=vim
alias bashidea=". /home/idea/bashrc_idea"
alias bashideadev=". /home/idea/bashrc_ideadev"
alias sertools="cd /home/NikiraServerTools"
alias inslog="cd /home/nikira_v7/softwares/InstallLogs/"
alias clienttools="cd /home/NikiraClientTools"
alias sbin="cd $RANGERHOME/sbin"
alias ser="cd /home/idea/ROCFraudManagement-7.4.2/Server"
alias s="sqlplus $DB_USER/$DB_PASSWORD"
alias sp="sqlplus $SPARK_DB_USER/$SPARK_DB_PASSWORD"
alias src="cd /home/idea/ROCFraudManagement-7.4.2/Client/src"
alias not="cd /home/idea/ROCFraudManagement-7.4.2Client/notificationmanager"
alias slogs="tail -100f /home/idea/ROCFraudManagement-7.4.2/Client/notificationmanager/app_logs/server/all_modules_all_users_all_ips.log"
alias l="ls -lrt --color=auto"
alias ls="ls --color=auto"
alias cust="cd /home/idea/ROCFraudManagement-7.4.2/Customizations/Datasource/IDEA"
alias data="cd $NIKIRAROOT/FMSData"
alias inmem="cd $NIKIRAROOT/InMemory/"
