CREATE TABLE OUTROAMER_GPRS_VPMN_RATES(
	VPMN VARCHAR2(50) NOT NULL,
	VPMN_TYPE VARCHAR2(20) NOT NULL,
	PULSE NUMBER(5) NOT NULL,
	VALUE NUMBER(10,2) NOT NULL,
	CONSTRAINT OUTROAMER_VPMN_TYPE_CONSTRAINT CHECK( LOWER(VPMN_TYPE) IN ('international', 'national') ) );

COMMIT;
