/**
*
* (c) Copyright 1993-2009 Hewlett-Packard Development Company, L.P.
*
* @ingroup   OmniBack II - SAP R/3 BAR Integration
* @file      integ/sapnt/sapback.c
*
* @par Last Change:
* $Rev$
* $Date$
*
* @brief     OmniBack II-SAP R/3 integration backup agent. Accepts a list
*            of parameters (described below) through the command line and
*            a list of filenames through stdin and backs
*            them up, reporting all errors and the success of each file to
*            stdout. The cli options are:
*
*            argv[1]     = setName (as generated by backint SM)
*            argv[2]     = inFile  (optional, as generated by backint SM)
*
*            If no 2nd argument (inFile) is specified, the sapback program
*            reads its list of filenames from stdin.
*
*            The sapback program writes to stdout various messages, the type
*            of the message is indicated with a single character within brackets
*            at the start of each message. The following messages are defined:
*
*            s <sessID>              = BAR Client's session ID
*            b <barName>             = BAR Client's barName
*            + fileName              = file backed up successfully
*            - fileName              = file backed up unsuccessfully
*            e message "error text"  = generic error message
*            v anyText               = verbose report message
*
*            All message types are single-line messages and are parsable by
*            filters like awk(1).
*/

#include "lib/cmn/target.h"

#ifndef lint
static tchar rcsId[] = _T("$Header: /integ/sapnt/sapback.c $Rev$ $Date::                      $:") ;
#endif

#include <stdio.h>
#include <string.h>
#include <time.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <winbase.h>         /* ZQ for mutex & sleep */
#include <winsock.h>
#include <io.h>

#include "lib/cmn/common.h"
#include "da/bda/bda.h"      /* because of the uid_t defines */
#include "integ/bar2/libbar.h"
#include "integ/bar2/ob2common.h"

#include "sapback.h"
#include "integ/sap/commonmsg.h"
#include "integ/sap/sap_common.h"


/*========================================================================*//**
*
* @ingroup   SAP-Integration
*
* @param     msg
*
* @brief     NULL callback function for reporting
*
*//*=========================================================================*/
static void
errCallbackNull (tchar *msg)
{
}


/*========================================================================*//**
*
* @ingroup   SAP-Integration
*
* @param     s       string to convert
*
* @brief     converts all uppercase characters to lovercase
*
*//*=========================================================================*/
void
lcase(tchar *s)
{
    while (*s)
    {
        if (isupper(*s))
            *s = tolower(*s);
        s++;
    }
}




/*========================================================================*//**
*
* @ingroup   SAP-Integration
*
* @param     path         points to full pathname ([drive:]/dir1/dir2/.../filename - any slash can be backslash)
*                         or remote share \\computer\share\dir1\dir2...\filename
*
* @brief     Converts drive: to /drive:; converts backslashes to slashes
*            or \\computer\share to *            computer:share (the double slash is singled by DBSM);
*            caller must FREE the result
*
* @remarks   This is only a temporary function; to be used until local drives can be written properly
*
*//*=========================================================================*/
tchar *
GetRightInput (tchar *origpath)
{
    ERH_FUNCTION (_T("GetRightInput"));

    tchar *p, *q;
    tchar *newpath = StrNewCopy(origpath);

    DbgFcnIn();

    while (p = strchr(newpath, _T('\\')))
    {
        *p = _T('/');
    }

/* ---------------------------------------------------------------------------
| handle drives
 -------------------------------------------------------------------------- */
    if (IsCharAlpha(newpath[0]) && (newpath[1] == _T(':')))
    {
        /* newwpath[1] = '\\'; */
        newpath = (tchar *) REALLOC(newpath, StrSize(newpath)+2); /*make space for one more*/
        q = newpath + StrLen(newpath);
        p = q + 1;

        /* move the string one tchar forward */
        while (p != newpath)
        {
            *p-- = *q--;
        }
        /* insert slash */
        *p = _T('/');
    }
/* ---------------------------------------------------------------------------
| handle UNCs
 -------------------------------------------------------------------------- */
    else if ((newpath[0] == _T('/')) && (newpath[1] == _T('/')))
    {/* let's move just the computer name on the left */
        p = strchr(newpath+2, _T('/'));

        q = newpath;
        while (++q != (p-1))
        {
            *q = *(q+1);
        }
        *q = _T(':');
    }

    DbgFcnOut();
    return (newpath);
}



/*========================================================================*//**
*
* @ingroup   SAP-Integration
*
* @param     path         points to full pathname ([/drive]/dir1/dir2/.../filename
*                         - any backslash can be slash)
*
* @brief     Converts /drive\ to /drive:; converts slashes to backslashes
*            or /computer\share to *            computer/share
*
* @remarks   This is only a temporary function; to be used until local drives
*            can be written properly
*
*//*=========================================================================*/
tchar *
GetRightOutput(tchar* origpath)
{
    ERH_FUNCTION (_T("GetRightOutput"));

    tchar *p, *q;
    tchar *newpath = MALLOC((STRLEN_PATH+1)*sizeof(tchar));

    DbgFcnIn();

    strcpy(newpath, origpath);

/* ---------------------------------------------------------------------------
| handle ZOKI drives - delete first '/'
 -------------------------------------------------------------------------- */
    if (IsCharAlpha(newpath[1]) && (newpath[2] == _T('\\')))
    {
        newpath[2] = _T(':');
        p = newpath;
        q = p + 1;
        while (*q)
        {
            *p++ = *q++;
        }
        *p = _T('\0');
    }
/* ---------------------------------------------------------------------------
| handle NEW drives (MARKUS)
 -------------------------------------------------------------------------- */
    else if (IsCharAlpha(newpath[1]) && (newpath[2] == _T(':')))
    {
        p = newpath;
        q = p + 1;
        while (*q)
        {
            *p++ = *q++;
        }
        *p = _T('\0');
    }
/* ---------------------------------------------------------------------------
| handle old drives - /c to c:
 -------------------------------------------------------------------------- */
    else if (IsCharAlpha(newpath[1]) && (newpath[2] == _T('/')))
    {
        newpath[0] = newpath[1];
        newpath[1] = _T(':');
    }
/* ---------------------------------------------------------------------------
| handle ZOKI UNCs - convert \ to /, insert / in front
 -------------------------------------------------------------------------- */
    else if (p = strchr(newpath, _T('\\')))
    {
        *p = _T('/');
        newpath = (tchar *) REALLOC(newpath, StrSize(newpath)+2);
        q = newpath + StrLen(newpath);
        p = q + 1;

        /* move the string one tchar forward */
        while (p != newpath)
        {
            *p-- = *q--;
        }
        /* insert slash */
        *p = _T('/');
    }
/* ---------------------------------------------------------------------------
| handle NEW UNCs
 -------------------------------------------------------------------------- */
    else if (p = strchr(newpath, _T(':')))
    {
      q = newpath+1;
      while(p != q)
      {
          *p = *(p-1);
          p--;
      }
      *p = _T('/');
    }
/* ---------------------------------------------------------------------------
| handle OLD UNCc
 -------------------------------------------------------------------------- */
    else /* what else can it be (heuristics) */
    {
        strcpy(newpath, _T("\\"));
        strcat(newpath, origpath);
    }

    while (p = strchr(newpath, _T('/')))
    {
        *p = _T('\\');
    }

    DbgFcnOut();
    return (newpath);
}



/*========================================================================*//**
*
* @ingroup   SAP-Integration
*
* @param     privilege_name
*
* @brief     Adds privelege privelege_name to the process.
*
*//*=========================================================================*/
int
Win32_SetPrivilege( tchar * privilege_name)
{
    ERH_FUNCTION(_T("Win32_SetPrivilege"));

    HANDLE hAccessToken = 0;
    int retcode = 0;

    DbgFcnIn();

    if (OpenProcessToken(
        GetCurrentProcess(),
        TOKEN_ADJUST_PRIVILEGES | TOKEN_QUERY,
        &hAccessToken))
    {
        LUID SeValue;
        int err;
        TOKEN_PRIVILEGES TokenPrivileges;

        retcode = LookupPrivilegeValue(NULL, privilege_name, &SeValue);

        if ( !retcode )
        {
            DbgStamp (DBG_UNEXPECTED);
            DbgPlain (DBG_UNEXPECTED,
                _T("[%s] LookupPrivilegeValue(NULL,   privilege_name=%s) failed. Error: %s"),
                __FCN__,
                privilege_name,
                ErhSysErrnoToText(GetLastError()) );

            ErhFullReport (
                __FCN__,
                ERH_MAJOR,
                NlsGetMessage(
                    NLS_SET_SAP,
                    NLS_CANNOT_LOOKUPPRIV,
                    privilege_name,
                    GetLastError()) );
        }
        else
        {
            TokenPrivileges.PrivilegeCount = 1;
            TokenPrivileges.Privileges[0].Luid = SeValue;
            TokenPrivileges.Privileges[0].Attributes = SE_PRIVILEGE_ENABLED;

            (VOID)
            AdjustTokenPrivileges (
                hAccessToken,
                FALSE,
                &TokenPrivileges,
                sizeof( TOKEN_PRIVILEGES ),
                NULL,
                NULL);

            err = GetLastError();

            if ( err != NO_ERROR )
            {
                DbgStamp (DBG_UNEXPECTED);
                DbgPlain (DBG_UNEXPECTED,
                    _T("[%s] AdjustTokenPrivileges() failed. Error: %s"),
                    __FCN__,
                    ErhSysErrnoToText(GetLastError()));

                ErhFullReport (
                    __FCN__,
                    ERH_MAJOR,
                    NlsGetMessage(
                        NLS_SET_SAP,
                        NLS_CANNOT_LOOKUPPRIV,
                        privilege_name,
                        GetLastError()) );

                retcode = 1;
            }
        }

        CloseHandle(hAccessToken);
    }
    else
    {
        int err= GetLastError();

        DbgStamp (DBG_UNEXPECTED);
        DbgPlain (DBG_UNEXPECTED,
            _T("[%s] OpenProcessToken() failed. Error: %s"),
            __FCN__,
            ErhSysErrnoToText(GetLastError()));

        DbgPlain (DBG_SAP_STATUS, _T("Cannot open process token - %d.\n"), err);
    }

    DbgFcnOut();

    return retcode;
}

/*========================================================================*//**
*
* @ingroup   SAP-Integration
*
* @param     string
*
* @brief     Cuts the string at the last \n character.
*
*//*=========================================================================*/
void
StripNewLine(tchar *str)
{
    tchar *c = strrchr(str, _T('\n'));

    if (c)
       *c = _T('\0');
}

/*========================================================================*//**
*
* @ingroup   SAP-Integration
*
* @param     string
*
* @brief     Checks the input line and determines if is needed by backup session.
*
*//*=========================================================================*/
int IsOutputNeeded (tchar *line)
{
    return
        strncmp (line, _T("#"), 1) == 0 ||
        strncmp (line, _T("BR0315I"), 7) == 0 ||
        strncmp (line, _T("BR0317I"), 7) == 0 ||
        strncmp (line, _T("BR0280I"), 7) == 0 ||
        strncmp (line, _T("BR315I"), 6) == 0 ||
        strncmp (line, _T("BR317I"), 6) == 0 ||
        strncmp (line, _T("BR280I"), 6) == 0;
}


/* ---------------------------------------------------------------------------
|
|    main: Backup files from stdin using OB2 BAR Services
|
 -------------------------------------------------------------------------- */
static tchar    *usageStr = _T("Usage: sapback <setName> <inFile>");

void
main (int argc, tchar *argv[])
{
    ERH_FUNCTION(_T("main"));

    ULONG        mode                           = 0;
    FILE        *inFile;
    tchar        path[STRLEN_PATH+1];
    tchar        *appName;
    tchar        *barList;
    tchar        objName[STRLEN_BAROBJNAME+1];
    tchar        setName[STRLEN_BAROBJNAME+1];
    int          back_type                      = FILE_OFFLINE;
    tchar        oraHome[STRLEN_PATH+1];
    int          state;
    size_t       size                           = BUFF_LEN; /* Changed from int to size_t (Matic) */
    int          space                          = BUFF_LEN;
    tchar       *ARG_FILELIST;
    tchar       *obFileName;
    tchar       *restype;

    HANDLE       hMutex                         = NULL;
    LPCTSTR      lpBrMutex                      = _T("brbackup_mutex");

    tchar        switchList[STRLEN_PATH+1];
    tchar        switchSem[STRLEN_PATH+1];
    tchar        switchLog[STRLEN_PATH+1];

    FILE        *fpList;
    FILE        *fpSem;
    FILE        *fpLog;

    WORD         wVersionRequested;
    WSADATA      wsaData;
    int          err;

    /* NEW semicolon functionality */
        size_t       dwListLen;   /* Changed from WORD to size_t (Matic) */
    tchar       *lpszFileList,
                *lpszFileListTmp,
                *lpszBuffer;
    BOOL         begin;

    tchar       **fileList=NULL;
    int         nFiles=0;
    int         i=0;

    OB2_CONTEXT  context;

    wVersionRequested = MAKEWORD(1,1);
    err = WSAStartup (wVersionRequested, &wsaData);
    if (err != 0)
    {
        DbgStamp (DBG_UNEXPECTED);
        DbgPlain (DBG_UNEXPECTED,
            _T("[%s] WSAStartup (wVersionRequested, &wsaData) failed. Error: %s"),
            __FCN__,
            ErhSysErrnoToText(GetLastError()));

        fprintf (stderr, _T("Sockets error: %d\n"), err);

        fflush (stderr);
        ExitProcess (err);
    }

    appName = BU_EnvGetStrValue(_T("OB2APPNAME"), _T("DEFAULT"));
    barList = BU_EnvGetStrValue(_T("OB2BARLIST"), _T("SAP-R3"));

    if (argc < 3)
    {
        tchar   verString[STRLEN_VERSION+1];

        CmnSetProgname(PROG_SAPBACK);
        MakeVersionString (STRLEN_VERSION, verString);
        ConPrintf (_T("%s\n"), verString);

        ExitProcess (1);
    }

/* ---------------------------------------------------------------------------
|    Initialise OB2 BAR Services
 -------------------------------------------------------------------------- */
    OB2_SetFlags(OB2_FENABLE_CLUSTERING);

    if (OB2_Init(OB2_APP_SAP, appName, _T("SAPBACK"), (vFs)errCallbackNull, &context))
    {
        DbgStamp (DBG_UNEXPECTED);
        DbgPlain (DBG_UNEXPECTED,
            _T("[%s] OB2_Init(OB2_APP_SAP, appName=%s, errCallBack) failed. Error: %s"),
            __FCN__,
            appName,
            ErhErrnoToText());

        ERR (_T("Cannot init OB2BAR"), context);

        inFile = fopen(ARG_INFILE, _T("r"));

        goto EXIT;
    }

    DbgFcnIn();

    if ((inFile = fopen(ARG_INFILE, _T("r"))) == NULL)
    {
        DbgStamp (DBG_UNEXPECTED);
        DbgPlain (DBG_UNEXPECTED,
            _T("[%s] fopen(ARG_INFILE=%s, \"r\") failed. Error: %s"),
            __FCN__,
            ARG_INFILE,
            ErhSysErrnoToText(GetLastError()));

        ConPrintf (OUT_ERROR, ARG_INFILE, strerror (errno));

        goto EXIT;
    }

    GetFilesListFromFile(inFile, &fileList, &nFiles);

    ARG_FILELIST = (tchar*)MALLOC((size+1)*sizeof(tchar));
    *ARG_FILELIST = _T('\0');

    for(i=0;i<nFiles;i++)
    {
        StrCopy(path, fileList[i], STRLEN_PATH);
        StripNewLine(path);

        obFileName = GetRightInput(path);

        space = space - StrLen(obFileName) - 1;

        if (space < 1)
        {
            size  += BUFF_LEN;
            space += BUFF_LEN;

            ARG_FILELIST = (tchar*)REALLOC(ARG_FILELIST, (size+1)*sizeof(tchar));
        }
        DbgPlain (DBG_SAP_INFO, _T("[%s] Adding (%d/%d): %s"), __FCN__, StrLen (obFileName), space, obFileName);
        ARG_FILELIST = strcat (ARG_FILELIST, obFileName);
        ARG_FILELIST = strcat (ARG_FILELIST, _T(" "));
        FREE (obFileName);
    }
    rewind(inFile);

    if (OB2_StartBackup(context, barList) != OBE_OK)
    {
        DbgStamp (DBG_UNEXPECTED);
        DbgPlain (DBG_UNEXPECTED,
            _T("[%s] OB2_StartBackup(context, barList==%s) failed!"),
            __FCN__,
            barList);

        ErhFullReport(
            __FCN__,
            ERH_CRITICAL,
            NlsGetMessage(
                NLS_SET_SAP,
                NLS_SAP_START_BACKUP_FAILED,
                barList,
                ErhErrnoToText()));
        ErhClearError();

        ERR ( NlsGetMessage (
                             NLS_SET_SAP,
                                 NLS_SAP_CANNOT_START_BACKUP),
                                 context);

        goto EXIT;
    }

    DbgPlain (DBG_SAP_INFO, _T("[%s] OB2APPNAME=%s, appName=%s"), __FCN__, getenv(_T("OB2APPNAME")), appName);
    DbgPlain (DBG_SAP_INFO, _T("[%s] OB2BARLIST=%s, barList=%s"), __FCN__, getenv(_T("OB2BARLIST")), barList);
    DbgPlain (DBG_SAP_INFO, _T("[%s] SAPBACKUP=%s"), __FCN__, getenv(_T("SAPBACKUP")));
    DbgPlain (DBG_SAP_INFO, _T("[%s] sapback arguments:\n\t%s"), __FCN__, GetCommandLine());

    Win32_SetPrivilege( SE_BACKUP_NAME );

    if (argc == 4)
    {
        back_type = FILE_ONLINE;

        if ((GetEnvironmentVariable(_T("SAPBACKUP"), oraHome, STRLEN_PATH+1) == 0) ||
            (*oraHome == _T('\0')))
        {

            DbgStamp (DBG_UNEXPECTED);
            DbgPlain (DBG_UNEXPECTED,
                _T("[%s] GetEnv(SAPBACKUP) failed. Error: %s"),
                __FCN__,
                ErhSysErrnoToText(GetLastError()));

           goto EndBackEXIT;
        }

        sprintf (switchList,_T("%s\\%s"), oraHome, SAP_SWITCHLIST);
        sprintf (switchSem, _T("%s\\%s"), oraHome, SAP_SWITCHSEM);
        sprintf (switchLog, _T("%s\\%s"), oraHome, SAP_SWITCHLOG);

        DbgPlain(DBG_SAP_INFO, _T("Switch files:"));
        DbgPlain(DBG_SAP_INFO, _T("Switch-list: '%s', Switch-semaphore: '%s', Switch-log: '%s'"),
                                switchList, switchSem, switchLog );

        if ((hMutex = OpenMutex (SYNCHRONIZE, TRUE, lpBrMutex)) == NULL)
        {
            DbgStamp (DBG_UNEXPECTED);
            DbgPlain (DBG_UNEXPECTED,
                _T("[%s] OpenMutex (SYNCHRONIZE, TRUE, lpBrMutex) failed. Error: %s"),
                __FCN__,
                ErhSysErrnoToText(GetLastError()));

           ErhFullReport (
                __FCN__,
                ERH_CRITICAL,
                NlsGetMessage(
                    NLS_SET_SAP,
                    NLS_CANNOT_OPENMUTEX,
                    GetLastError()) );

           goto EndBackEXIT;
        }
    }

    DbgPlain(DBG_SAP_FLOW, _T("[%s] Backup type: %d, %s"),
        __FCN__, back_type, back_type == FILE_ONLINE ? _T("FILE_ONLINE") : back_type == FILE_OFFLINE ? _T("FILE_OFFLINE") : _T("UNKNOWN"));

/* ---------------------------------------------------------------------------
|    Create new backup set
 -------------------------------------------------------------------------- */
    fflush (stdout); fflush (stderr);

    sprintf (setName, _T("%.*s"), STRLEN_BAROBJNAME, ARG_SETNAME);

    /* NEW semicolon functionality */

    DbgStamp (DBG_SAP_INFO);

    dwListLen       = StrSize(ARG_FILELIST);
    lpszFileList    = MALLOC(dwListLen*2);
    ZeroMemory (lpszFileList, dwListLen*2);
    *lpszFileList   = _T('\0');
    space           = dwListLen*2;
    size            = dwListLen*2;
    begin           = FALSE;
    lpszFileListTmp = ARG_FILELIST;
    lpszBuffer      = MALLOC(3*sizeof(tchar));

    DbgPlain (DBG_SAP_INFO,
        _T("[%s] SEMICOLON:Argument FILELIST:\n%s\n"),
        __FCN__,
        ARG_FILELIST);

    DbgPlain (DBG_SAP_INFO ,
        _T("[%s] SEMICOLON:FILELIST length: %d\n"),
        __FCN__,
        dwListLen);


    strcpy(lpszFileList, _T("\""));

    while(*lpszFileListTmp)
    {
        if ((space=(space-3)) < 1)
        {
            size  += dwListLen;
            space += dwListLen;

            lpszFileList = (tchar*)REALLOC(lpszFileList, (size+1)*sizeof(tchar));
        }

       if (isspace(*lpszFileListTmp))
       {
          strcat(lpszFileList, _T("\"\n\""));
       }
       else
       {
            sprintf(lpszBuffer, _T("%c"), *lpszFileListTmp);
            strcat(lpszFileList, lpszBuffer);
       }
       lpszFileListTmp++;
    }
    /* there is always additional '\n' on the end of the list */
    lpszFileList[StrLen(lpszFileList)-2] = _T('\0');

    lcase(lpszFileList);

    DbgStamp (DBG_SAP_FLOW);
    DbgPlain (DBG_SAP_FLOW, _T("[%s] FILELIST: \n %s"), __FCN__, lpszFileList);

    sprintf (setName, _T("%.*s"), STRLEN_BAROBJNAME, ARG_SETNAME);

    restype = strtok(ARG_SETNAME, _T("."));
    restype = strtok(NULL, _T(" "));

    DbgPlain (DBG_SAP_FLOW,
        _T("[%s] Calling StartObjectBackup %s\n"),
        __FCN__,
        restype);


    if (OB2_StartObjectBackup(
            context,
            OT_OB2BAR,
            cmnHostname,
            setName,
            BT_FULL,
            lpszFileList,
            restype,
            SF_LOG,
            NULL,
            NULL)!=OBE_OK)
    {
        DbgStamp (DBG_UNEXPECTED);
        DbgPlain (DBG_UNEXPECTED,
            _T("[%s] OB2_StartObjectBackup(appName=%s, barList=%s) failed. Error: %s"),
            __FCN__,
            appName,
            barList,
            ErhErrnoToText());

        ErhFullReport(
            __FCN__,
            ERH_CRITICAL,
            NlsGetMessage(
                NLS_SET_SAP,
                NLS_SAP_START_OBJ_BACKUP_FAILED,
                setName,
                ErhErrnoToText()));
        ErhClearError();

        ERR ( NlsGetMessage (
                             NLS_SET_SAP,
                                 NLS_SAP_CANNOT_CREATE_BACKUP_SET),
                                 context);

        mode=1;

        goto EndBackEXIT;
    }

    StrToObjectName(
        OT_OB2BAR,
        cmnHostname,
        setName,
        OB2_APP_SAP,
        objName);

    ConPrintf (OUT_BARNAME, objName);
    ConPrintf (OUT_SESSION, OB2_SessionID(context));

    DbgPlain (DBG_SAP_INFO, _T("[%s] Objectname: '%s'"), __FCN__, objName);

/* ---------------------------------------------------------------------------
|    Read filenames from inFile until EOF
 -------------------------------------------------------------------------- */
    for(i=0;(i<nFiles) && !mode;i++)
    {
        OB2_Stat    obstat;
        OFF_T64         size = 0L;
        int             co   = 0;
        OB2_Item        item = {0};
        HANDLE          fd;
        struct _stati64 st;
        tchar           *pathSlashed,
                        *name;
        LARGE_INTEGER   liFileSize;

        StrCopy(path, fileList[i], STRLEN_PATH);
        StripNewLine(path);

        DbgPlain (DBG_SAP_INFO, _T("[%s] file to stat: %s"), __FCN__, path);

        name = StrNewCopy(path);

        if (_tstati64(name, &st))
        {
            DbgStamp (DBG_UNEXPECTED);
            DbgPlain (DBG_UNEXPECTED,
                _T("[%s] _tstat(name=%s) failed. Error: %s"),
                __FCN__,
                name,
                ErhSysErrnoToText(GetLastError()));

            ErhFullReport (
                __FCN__,
                ERH_CRITICAL,
                NlsGetMessage(
                    NLS_SET_SAP,
                    NLS_SAP_CANNOT_STAT,
                    name,
                    GetLastError()) );

            ConPrintf (OUT_FAILURE, path);
            mode = 1;

            continue;
        }

        DbgPlain (DBG_SAP_INFO, _T("[%s] file mode is: %d"), __FCN__, st.st_mode);

        OB2_StatFile (path, &obstat);
        OB2_StatToItem (&obstat, &item);

        fd = CreateFile(path, GENERIC_READ,
                (FILE_SHARE_READ | FILE_SHARE_WRITE),
                NULL,
                OPEN_EXISTING,
                FILE_ATTRIBUTE_NORMAL| FILE_FLAG_BACKUP_SEMANTICS ,
                NULL);

        if (GetLastError() != NO_ERROR)
        {
            DbgStamp (DBG_UNEXPECTED);
            DbgPlain (DBG_UNEXPECTED,
                _T("[%s] CreateFile(path=%s, OPEN_EXISTING) failed. Error: %s"),
                __FCN__,
                path,
                ErhSysErrnoToText(GetLastError()));

            ErhFullReport(
                __FCN__,
                ERH_MAJOR,
                NlsGetMessage(
                    NLS_SET_SAP,
                    NLS_SAP_OPEN_FILE_FAIL,
                    path,
                    GetLastError()));

            mode = 1;
        }
        else
        {
            liFileSize.LowPart = GetFileSize(fd, &liFileSize.HighPart);

            CloseHandle(fd);

            if (liFileSize.LowPart == 0xFFFFFFFF && (GetLastError() != NO_ERROR ))
            {
                DbgStamp (DBG_UNEXPECTED);
                DbgPlain (DBG_UNEXPECTED,
                    _T("[%s] GetFileSize(path=%s) failed. Error: %s"),
                    __FCN__,
                    path,
                    ErhSysErrnoToText(GetLastError()));

                ErhFullReport (
                    __FCN__,
                    ERH_MAJOR,
                    NlsGetMessage(
                        NLS_SET_SAP,
                        NLS_CANNOT_GET_FILE_SIZE,
                        path,
                        GetLastError()) );

                mode = 1;
            }

            item.attr.size = liFileSize.QuadPart;
            item.attr.mode = GetFileAttributes(path);

            if( item.attr.mode == 0xFFFFFFFF)
            {
                DbgStamp (DBG_UNEXPECTED);
                DbgPlain (DBG_UNEXPECTED,
                    _T("[%s] GetFileAttributes(path=%s) failed. Error: %s"),
                    __FCN__,
                    path,
                    ErhSysErrnoToText(GetLastError()));

                ErhFullReport (
                    __FCN__,
                    ERH_MAJOR,
                    NlsGetMessage(
                        NLS_SET_SAP,
                        NLS_CANNOT_GET_ATTR,
                        path,
                        GetLastError()) );

                mode = 1;
            }
        }

/* ---------------------------------------------------------------------------
|    Classify filesystem object and process it if supported
 -------------------------------------------------------------------------- */
        switch (st.st_mode & S_IFMT)
        {
            case S_IFCHR:   item.type = OBJ_CDEV;   break;
            case S_IFREG:   item.type = OBJ_FILE;   break;
            case S_IFDIR:   item.type = OBJ_DIR;    break;
            default:
                DbgStamp (DBG_UNEXPECTED);
                DbgPlain (DBG_UNEXPECTED,
                    _T("[%s] Filesystem object unclassified. type = %d"),
                    __FCN__,
                    st.st_mode & S_IFMT);

                ConPrintf (OUT_FAILURE, path);

                continue;
        }

/* ---------------------------------------------------------------------------
|    Create new backup object
 -------------------------------------------------------------------------- */
        pathSlashed = GetRightInput (path);
        lcase(pathSlashed);
        sprintf (item.name, _T("%.*s"), STRLEN_OBJNAME, pathSlashed);
        FREE (pathSlashed);

        DbgPlain (DBG_SAP_INFO, _T("[%s] object name is: %s"), __FCN__, item.name);

        if (back_type == FILE_ONLINE)
        {
            int i = 0;
            DbgPlain (DBG_SAP_INFO, _T("[%s] Entering actual online backup"), __FCN__);

/* ---------------------------------------------------------------------------
|      Wait for mutex and grab it
 -------------------------------------------------------------------------- */
            DbgStamp (DBG_SAP_FLOW);
            DbgPlain (DBG_SAP_FLOW, _T("Waiting for the Mutex INFINITE."));

            if (WaitForSingleObject (hMutex, INFINITE) != WAIT_OBJECT_0)
            {
                DbgStamp (DBG_UNEXPECTED);
                DbgPlain (DBG_UNEXPECTED,
                    _T("[%s] WaitForSingleObject() failed. Error: %s"),
                    __FCN__,
                    ErhSysErrnoToText(GetLastError()));

                ErhFullReport (
                    __FCN__,
                    ERH_MAJOR,
                    NlsGetMessage(
                        NLS_SET_SAP,
                        NLS_CANNOT_WAITMUTEX,
                        GetLastError()) );

                mode = 1;

                break;
            }

            DbgStamp (DBG_SAP_FLOW);
            DbgPlain (DBG_SAP_FLOW, _T("Got mutex."));

/* ---------------------------------------------------------------------------
|        Create switchList file
 -------------------------------------------------------------------------- */

            DbgPlain(DBG_SAP_FLOW, _T("Creating Switch-list file '%s'."), switchList);

            if ((fpList = fopen (switchList, _T("w"))) == NULL)
            {
                DbgStamp (DBG_UNEXPECTED);
                DbgPlain (DBG_UNEXPECTED,
                    _T("[%s] fopen(switchList=%s, \"w\") failed. Error: %s"),
                    __FCN__,
                    switchList,
                    ErhSysErrnoToText(GetLastError()));

                ErhFullReport (
                    _T("main"),
                    ERH_MAJOR,
                    NlsGetMessage(
                        NLS_SET_SAP,
                        NLS_CANNOT_OPEN_SWITCHLIST,
                        GetLastError()) );

                mode = 1;

                break;
            }
            fprintf (fpList, SAP_BEGIN, path);
            fclose (fpList);

            DbgStamp (DBG_SAP_FLOW);
            DbgPlain (DBG_SAP_FLOW, _T("Switch-list file content:"));
            DbgPlain (DBG_SAP_FLOW, SAP_BEGIN, path);

/* ---------------------------------------------------------------------------
|        Create switchSem file
 -------------------------------------------------------------------------- */
            DbgStamp (DBG_SAP_FLOW);
            DbgPlain (DBG_SAP_FLOW, _T("Creating Switch-semaphore file '%s'."), switchSem);

            if ((fpSem = fopen (switchSem, _T("w"))) == NULL)
            {
                DbgStamp (DBG_UNEXPECTED);
                DbgPlain (DBG_UNEXPECTED,
                    _T("[%s] fopen(switchSem=%s, \"w\") failed. Error: %s"),
                    __FCN__,
                    switchSem,
                    ErhSysErrnoToText(GetLastError()));

                ErhFullReport (
                    _T("main"),
                    ERH_MAJOR,
                    NlsGetMessage(
                        NLS_SET_SAP,
                        NLS_CANNOT_OPEN_SEMLIST,
                        GetLastError()) );

                mode = 1;

                break;
            }
            fprintf (fpSem, _T("\n"));
            fclose  (fpSem);

            DbgStamp (DBG_SAP_FLOW);
            DbgPlain (DBG_SAP_FLOW, _T("The Switch-semaphore file is created."));

/* ---------------------------------------------------------------------------
|        Wait until switchSem file is deleted
 -------------------------------------------------------------------------- */
            DbgPlain (DBG_SAP_FLOW,
                _T("[%s] Waiting until Switch-semaphore file is deleted..."),
                __FCN__);

            while (i++ <= MAX_POLL_ITERATIONS)
            {
                sleep (POLL_SLEEP);
                if (OB2_StatFile(switchSem, NULL) == -1)
                {
                    DbgStamp (DBG_SAP_FLOW);
                    DbgPlain (DBG_SAP_FLOW, _T("File deleted."));
                    break;
                }
            }

            state = STATE_UNDEF;

            if (i > MAX_POLL_ITERATIONS)
            {
                DbgStamp (DBG_UNEXPECTED);
                DbgPlain (DBG_UNEXPECTED,
                    _T("[%s] Error: Brbackup doesn't respond (i>%d). No Error."),
                    __FCN__, MAX_POLL_ITERATIONS);

                ErhFullReport (
                    __FCN__,
                    ERH_MAJOR,
                    NlsGetMessage(
                        NLS_SET_SAP,
                        NLS_BRBACKUP_HANG) );

                mode = 1;
            }
            else
            {
                tchar line[1024];
/* ---------------------------------------------------------------------------
|      Parsing switch log file
 -------------------------------------------------------------------------- */
                DbgStamp (DBG_SAP_FLOW);
                DbgPlain (DBG_SAP_FLOW, _T("[%s] Brbackup responded"), __FCN__);
                DbgPlain (DBG_SAP_FLOW, _T("Parsing Switch-log file '%s'."), switchLog);

                if ((fpLog = fopen (switchLog, _T("r"))) == NULL)
                {
                    DbgStamp (DBG_UNEXPECTED);
                    DbgPlain (DBG_UNEXPECTED,
                        _T("[%s] fopen(switchLog=%s, \"r\") failed. Error: %s"),
                        __FCN__,
                        switchLog,
                        ErhSysErrnoToText(GetLastError()));

                     ErhFullReport (
                        _T("main"),
                        ERH_MAJOR,
                        NlsGetMessage(
                            NLS_SET_SAP,
                            NLS_CANNOT_OPEN_LOGLIST,
                            GetLastError()) );

                    mode = 1;

                    break;
                }

                DbgStamp (DBG_SAP_FLOW);
                DbgPlain (DBG_SAP_FLOW, _T("I'll grep for #SUCCESS, #ERROR, or other."));

                while (fgets (line, 1024, fpLog))
                {
                    DbgPlain(DBG_SAP_INFO, _T("line: '%s'"), line);

                    if (strncmp (line, _T("#SUCCESS"), 8) == 0)
                    {
                        state = STATE_SUCCESS;
                        DbgPlain (DBG_SAP_INFO, _T("Matched #SUCCESS"));
                    }
                    else if (strncmp (line, _T("#ERROR"), 6) == 0)
                    {
                        state = STATE_ERROR;
                        DbgPlain (DBG_SAP_INFO, _T("Matched #ERROR"));
                    }
                    else
                    {
                        if (IsOutputNeeded(line))
                        {
                            printf (OUT_VERBOSE, line);
                        }
                    }
                }

                fclose (fpLog);

                if (back_type == FILE_ONLINE)
                {
                    /* ---------------------------------------------------------------------------
                    |        Create switcList file
                    -------------------------------------------------------------------------- */
                    fpList = fopen (switchList, _T("w"));
                    if (!fpList)
                    {
                        DbgStamp (DBG_UNEXPECTED);
                        DbgPlain (DBG_UNEXPECTED,
                            _T("[%s] fopen(switchList=%s, \"w\") failed. Error: %s"),
                            __FCN__,
                            switchList,
                            ErhSysErrnoToText(errno));
                    }

                    fprintf (fpList, SAP_END, path);
                    fclose (fpList);

                    /* ---------------------------------------------------------------------------
                    |        Wait until switchSem file is deleted
                    -------------------------------------------------------------------------- */

                    DbgStamp (DBG_SAP_FLOW);
                    DbgPlain (DBG_SAP_FLOW, _T("I'll delete switchlog file."));

                    if (DeleteFile (switchLog) == FALSE)
                    {
                        int err = GetLastError();

                        DbgStamp (DBG_UNEXPECTED);
                        DbgPlain (DBG_UNEXPECTED,
                            _T("[%s] DeleteFile(switchLog=%s) failed at BEGIN. Error: %s"),
                            __FCN__,
                            switchLog,
                            ErhSysErrnoToText(err));

                        ErhFullReport(
                            __FCN__,
                            ERH_MINOR,
                            NlsGetMessage(
                            NLS_SET_SAP,
                            NLS_SAP_DELETE_FAILED,
                            switchLog,
                            ErhSysErrnoToText(err)));
                    }
                    else
                    {
                        DbgStamp (DBG_SAP_FLOW);
                        DbgPlain (DBG_SAP_FLOW,
                            _T("[%s] Successfully deleted SWITCH log file."),
                            __FCN__);
                    }
                }

            }
            /* ---------------------------------------------------------------------------
            |      Release mutex
            -------------------------------------------------------------------------- */
            DbgStamp (DBG_SAP_FLOW);
            DbgPlain (DBG_SAP_FLOW, _T("I'll release mutex!!"));

            if (ReleaseMutex (hMutex) == FALSE)
            {

                DbgStamp (DBG_UNEXPECTED);
                DbgPlain (DBG_UNEXPECTED,
                    _T("[%s] ReleaseMutex() failed. Error: %s"),
                    __FCN__,
                    ErhSysErrnoToText(GetLastError()));

                ErhFullReport (
                    _T("main"),
                    ERH_MAJOR,
                    NlsGetMessage(
                        NLS_SET_SAP,
                        NLS_CANNOT_RELEASE_MUTEX,
                        GetLastError()) );

                mode = 1;

                break;
            }

            DbgStamp(DBG_SAP_FLOW);
            DbgPlain (DBG_SAP_FLOW, _T("[%s] ReleaseMutex succeeded\n"), __FCN__);

            if (state != STATE_SUCCESS)
            {
                break;
            }
        }

        {
            /*long*/
                        time_t    timeStart, timeDur;

            DbgPlain (DBG_SAP_FLOW,
                _T("[%s] Before OB2_StartItemBackup(%s)"),
                __FCN__,
                item.name);

            timeStart = time(NULL);

            /* QXCR1000413631 - if item.flags are going to be used, remove the hardcoding from ntvrda.c */
            if (OB2_StartItemBackup(context,&item, NULL, 0, 0L))
            {
                DbgStamp (DBG_UNEXPECTED);
                DbgPlain (DBG_UNEXPECTED,
                    _T("[%s] OB2_StartItemBackup(item.name=%s) ")
                    _T("failed. Error: %s\nGetRightOutput(name)=%s"),
                    __FCN__,
                    item.name,
                    ErhErrnoToText(),
                    GetRightOutput(item.name));

                ErhFullReport(
                    __FCN__,
                    ERH_MAJOR,
                    NlsGetMessage(
                        NLS_SET_SAP,
                        NLS_SAP_START_ITEM_BACKUP_FAILED,
                        item.name,
                        ErhErrnoToText()));
                ErhClearError();

                ConPrintf (OUT_FAILURE, path);

                mode = 1;

                continue;
            }

/* ---------------------------------------------------------------------------
|     Backup regular UNIX flat directory, not the subdirectories
 -------------------------------------------------------------------------- */

            if (item.type == OBJ_DIR)
            {
                HANDLE          hFind;
                WIN32_FIND_DATA finddata;
                tchar           szDirectoryName[STRLEN_PATH+1];
                tchar           nameFile[STRLEN_STD+1];
                tchar           extPath[STRLEN_PATH+1];
                tchar          *name;
                int             result = 1; /* ==1 if the directory (ALL files) backed up correctly,
                                             ==0 otherwise */

                if (OB2_EndItemBackup(context, OB2_GetErrno(context)) != OBE_OK)
                {
                    DbgStamp (DBG_UNEXPECTED);
                    DbgPlain (DBG_UNEXPECTED,
                        _T("[%s] OB2_EndItemBackup() failed!"),
                        __FCN__);

                    ConPrintf (OUT_FAILURE, path);

                    continue;
                }

                strcpy(szDirectoryName, path);
                strcpy(extPath, path);
                strcat(extPath, _T("\\*"));

                if ((hFind = FindFirstFile(extPath, &finddata)) == INVALID_HANDLE_VALUE)
                {
                    DbgStamp (DBG_UNEXPECTED);
                    DbgPlain (DBG_UNEXPECTED,
                        _T("[%s] FindFirstFile(extPath=%s) failed. Error: %s"),
                        __FCN__,
                        extPath,
                        ErhSysErrnoToText(GetLastError()));

                    ErhFullReport(
                        __FCN__,
                        ERH_MINOR,
                        NlsGetMessage(
                            NLS_SET_SAP,
                            NLS_SAP_FIND_FAILED,
                            extPath));

                    ConPrintf (OUT_FAILURE, path);

                    continue;
                }
                else
                {
                    while (1)
                    {
                        if (!( (finddata.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) &&
                               (
                                 (!strcmp(finddata.cFileName,_T("."))) ||
                                 (!strcmp(finddata.cFileName,_T("..")))
                               )
                             )
                           )
                        {
                            sprintf(nameFile, _T("%s\\%s"), szDirectoryName, finddata.cFileName);
                            name = StrNewCopy(nameFile);
                            if (_tstati64 (name, &st))
                            {
                                DbgStamp (DBG_UNEXPECTED);
                                DbgPlain (DBG_UNEXPECTED,
                                    _T("[%s] name = %s"),
                                    __FCN__,
                                    name);

                                ErhFullReport(
                                    __FCN__,
                                    ERH_MAJOR,
                                    NlsGetMessage(
                                        NLS_SET_SAP,
                                        NLS_SAP_CANNOT_STAT,
                                        name,
                                        GetLastError()));

                                result = 0;

                                continue;
                            }

                            item.attr.uid    = st.st_uid;
                            item.attr.gid    = st.st_gid;
                            item.attr.mode   = GetFileAttributes(name);
                            if( item.attr.mode == 0xFFFFFFFF)
                            {
                                DbgStamp (DBG_UNEXPECTED);
                                DbgPlain (DBG_UNEXPECTED,
                                    _T("[%s] GetFileAttributes(name=%s) failed. Error: %s"),
                                    __FCN__,
                                    name,
                                    ErhSysErrnoToText(GetLastError()));

                                ErhFullReport (
                                    __FCN__,
                                    ERH_MAJOR,
                                    NlsGetMessage(
                                        NLS_SET_SAP,
                                        NLS_CANNOT_GET_ATTR,
                                        name,
                                        GetLastError()) );

                                result = 0;
                            }
                            item.attr.modifTime = st.st_mtime;

                            fd = CreateFile(name,
                                    GENERIC_READ,
                                    (FILE_SHARE_READ | FILE_SHARE_WRITE),
                                    NULL,
                                    OPEN_EXISTING,
                                    FILE_ATTRIBUTE_NORMAL | FILE_FLAG_BACKUP_SEMANTICS ,
                                    NULL);
                            if (GetLastError() != NO_ERROR)
                            {
                                DbgStamp (DBG_UNEXPECTED);
                                DbgPlain (DBG_UNEXPECTED,
                                    _T("[%s] CreateFile(path=\"%s\", OPEN_EXISTING) failed. Error: %s"),
                                    __FCN__,
                                    path,
                                    ErhSysErrnoToText(GetLastError()));

                                ErhFullReport(
                                    __FCN__,
                                    ERH_MAJOR,
                                    NlsGetMessage(
                                        NLS_SET_SAP,
                                        NLS_SAP_CANNOT_OPEN_FILE,
                                        name,
                                        GetLastError()));
                            }

                            liFileSize.LowPart = GetFileSize(fd, &liFileSize.HighPart);

                            CloseHandle(fd);

                            if (liFileSize.LowPart == 0xFFFFFFFF && (GetLastError() != NO_ERROR ))
                            {
                                DbgStamp (DBG_UNEXPECTED);
                                DbgPlain (DBG_UNEXPECTED,
                                    _T("%s: GetFileSize(path=%s) failed. Error: %s"),
                                    __FCN__,
                                    name,
                                    ErhSysErrnoToText(GetLastError()));

                                ErhFullReport (
                                    __FCN__,
                                    ERH_MAJOR,
                                    NlsGetMessage(
                                        NLS_SET_SAP,
                                        NLS_CANNOT_GET_FILE_SIZE,
                                        extPath,
                                        GetLastError()) );

                                result = 0;
                            }

                            item.attr.size = liFileSize.QuadPart;

/* ---------------------------------------------------------------------------
|     Classify filesystem object and process it if supported
 -------------------------------------------------------------------------- */
                            switch (st.st_mode & S_IFMT)
                            {
                            case S_IFCHR:    item.type = OBJ_CDEV;    break;
                            case S_IFREG:    item.type = OBJ_FILE;    break;
                            case S_IFDIR:    item.type = OBJ_DIR;     break;
                            default:
                                DbgStamp (DBG_UNEXPECTED);
                                DbgPlain (DBG_UNEXPECTED,
                                    _T("[%s] Filesystem object unclassified. type = %d"),
                                    __FCN__,
                                    st.st_mode & S_IFMT);

                                result = 0;
                                continue;
                            }

                            pathSlashed = GetRightInput (name);
                            lcase(pathSlashed);
                            sprintf (item.name, _T("%.*s"), STRLEN_OBJNAME, pathSlashed);
                            FREE (pathSlashed);

                            if (OB2_StartItemBackup(context,&item, NULL, 0, 0L))
                            {
                                DbgStamp (DBG_UNEXPECTED);
                                DbgPlain (DBG_UNEXPECTED,
                                    _T("%s: OB2_StartItemBackup(item.name=%s)")
                                    _T("failed. Error: %s"),
                                    __FCN__,
                                    item.name,
                                    ErhSysErrnoToText(GetLastError()));

                                ErhFullReport(
                                    __FCN__,
                                    ERH_MAJOR,
                                    NlsGetMessage(
                                        NLS_SET_SAP,
                                        NLS_SAP_START_ITEM_BACKUP_FAILED,
                                        item.name,
                                        ErhErrnoToText()));
                                ErhClearError();

                                result = 0;
                                continue;
                            }
                            if (item.type == OBJ_FILE)
                            {
                                if (item.attr.size > 0)
                                {
                                    FILEHANDLE fh;
                                    tchar      *fsName;

                                    if ((fsName = GetRightOutput(item.name))==NULL)
                                    {
                                        DbgStamp (DBG_UNEXPECTED);
                                        DbgPlain (DBG_UNEXPECTED,
                                            _T("%s: GetRightOutput(%s,0,0) failed. Error: %s"),
                                            __FCN__,
                                            item.name,
                                            ErhErrnoToText());

                                        result = 0;
                                    }
                                    else
                                    {
                                        if ((fh = OB2_Win32OpenFile(fsName,1,0))==NULL)
                                        {
                                            DbgStamp (DBG_UNEXPECTED);
                                            DbgPlain (DBG_UNEXPECTED,
                                                _T("[%s] OB2_Win32OpenFile(\"%s\") failed. Error: %s"),
                                                __FCN__,
                                                fsName,
                                                ErhErrnoToText());

                                            ErhFullReport(
                                                __FCN__,
                                                ERH_MAJOR,
                                                NlsGetMessage(
                                                    NLS_SET_SAP,
                                                    NLS_SAP_OPEN_FILE_FAIL,
                                                    fsName,
                                                    ErhErrno()));

                                            result = 0;
                                        }
                                        else
                                        {
                                            if (OB2_BackupFileItem(context,fh,&size)!=OBE_OK)
                                            {
                                                DbgStamp (DBG_UNEXPECTED);
                                                DbgPlain (DBG_UNEXPECTED,
                                                    _T("%s: OB2_BackupItem() failed. Error: %s"),
                                                    __FCN__,
                                                    ErhErrnoToText());

                                                result = 0;
                                            }
                                        }
                                        FREE(fsName);
                                        OB2_CloseFile(fh);
                                    }
                                }

                                DbgPlain (DBG_SAP_INFO,
                                    _T("[%s] In file size : %ld ; backed up file size : %ld "),
                                    __FCN__,
                                    (ULONG) item.attr.size,
                                    (ULONG) size);
                            }
                            if (OB2_EndItemBackup(context,OB2_GetErrno(context)))
                            {
                                DbgStamp (DBG_UNEXPECTED);
                                DbgPlain (DBG_UNEXPECTED,
                                    _T("[%s] OB2_EndItemBackup failed for %s"),
                                    __FCN__,
                                    path);

                                result = 0;
                            }
                            else
                            {
                                DbgStamp (DBG_SAP_FLOW);
                                DbgPlain (DBG_SAP_FLOW,
                                    _T("[%s] OB2_EndItemBackup succeeded for %s"),
                                    __FCN__,
                                    path);
                            }

                        }

                        if(FindNextFile(hFind,&finddata)!=TRUE)
                        {
                            if (GetLastError() != ERROR_NO_MORE_FILES)
                            {
                                DbgStamp (DBG_UNEXPECTED);
                                DbgPlain (DBG_UNEXPECTED,
                                    _T("[%s] FindNextFile() failed. Error: %s"),
                                    __FCN__,
                                    ErhSysErrnoToText(GetLastError()));

                                ErhFullReport(
                                    __FCN__,
                                    ERH_MINOR,
                                    NlsGetMessage(
                                    NLS_SET_SAP,
                                    NLS_SAP_FIND_FAILED,
                                    extPath));


                                result = 0;
                            }
                            break;
                        }
                    }

                    FindClose(hFind);
                    if (result)
                    {
                        DbgStamp (DBG_SAP_FLOW);
                        DbgPlain (DBG_SAP_FLOW, _T("[%s] Success."), __FCN__);

                        timeDur = time(NULL) - timeStart;
                        ConPrintf (OUT_SUCCESS_SPEED, path, timeDur?(item.attr.size/timeDur):(item.attr.size));
                    }
                    else
                    {
                        DbgStamp (DBG_SAP_FLOW);
                        DbgPlain (DBG_SAP_FLOW,
                            _T("[%s] Failure!"),
                            __FCN__);

                        ConPrintf(OUT_FAILURE, path);
                        mode = 1;
                    }
                    item.type=OBJ_DIR;
                }
            }

/* ---------------------------------------------------------------------------
|    Backup regular file, but only if not empty
 -------------------------------------------------------------------------- */
            if (item.type == OBJ_FILE)
            {
                int result = 1;  /* The same meaning as for dir backup */
                if (item.attr.size > 0)
                {
                    FILEHANDLE fh;
                    tchar      *fsName;

                    if ((fsName=GetRightOutput(item.name))==NULL)
                    {
                        DbgStamp (DBG_UNEXPECTED);
                        DbgPlain (DBG_UNEXPECTED,
                            _T("%s: GetRightOutput(%s,0,0) failed. Error: %s"),
                            __FCN__,
                            item.name,
                            ErhErrnoToText());

                        result = 0;
                    }
                    else
                    {
                        if ((fh = OB2_Win32OpenFile(fsName,1,0))==NULL)
                        {
                            DbgStamp (DBG_UNEXPECTED);
                            DbgPlain (DBG_UNEXPECTED,
                                _T("[%s] OB2_Win32OpenFile(\"%s\") failed. Error: %s"),
                                __FCN__,
                                fsName,
                                ErhSysErrnoToText(GetLastError()));

                            ErhFullReport(
                                __FCN__,
                                ERH_MAJOR,
                                NlsGetMessage(
                                    NLS_SET_SAP,
                                    NLS_SAP_CANNOT_OPEN_FILE,
                                    fsName,
                                    GetLastError()));

                            result = 0;
                        }
                        else if (OB2_BackupFileItem(context,fh,&size)!=OBE_OK)
                        {
                            DbgStamp (DBG_UNEXPECTED);
                            DbgPlain (DBG_UNEXPECTED,
                                _T("%s: OB2_BackupItem() failed. Error: %s"),
                                __FCN__,
                                ErhErrnoToText());

                            result = 0;
                        }

                        FREE(fsName);
                        OB2_CloseFile(fh);
                    }
                }

                DbgPlain (DBG_SAP_INFO,
                    _T("[%s] In file size : %ld ; backed up file size : %ld "),
                    __FCN__,
                    (ULONG) item.attr.size,
                    (ULONG) size);

/* ---------------------------------------------------------------------------
|    Complete current backup object ...
 -------------------------------------------------------------------------- */
                if (OB2_EndItemBackup(context,OB2_GetErrno(context)))
                {
                    DbgStamp (DBG_UNEXPECTED);
                    DbgPlain (DBG_UNEXPECTED,
                        _T("[%s] OB2_EndItemBackup failed for %s"),
                        __FCN__,
                        path);

                    result = 0;
                }
                else
                {
                    DbgStamp (DBG_SAP_FLOW);
                    DbgPlain (DBG_SAP_FLOW,
                        _T("[%s] OB2_EndItemBackup succeeded for %s"),
                        __FCN__,
                        path);
                }

                if (result)
                {
                    DbgStamp (DBG_SAP_FLOW);
                    DbgPlain (DBG_SAP_FLOW, _T("[%s] Success."), __FCN__);

                    timeDur=time(NULL) - timeStart;
                    ConPrintf (OUT_SUCCESS_SPEED, path, timeDur?(item.attr.size/timeDur):(item.attr.size));
                }
                else
                {
                    DbgStamp (DBG_SAP_FLOW);
                    DbgPlain (DBG_SAP_FLOW,
                        _T("[%s] Failure!"),
                        __FCN__);

                    ConPrintf(OUT_FAILURE, path);
                    mode = 1;
                }
            }
        }


        if (back_type == FILE_ONLINE)
        {
            int i = 0;
/* ---------------------------------------------------------------------------
|      Wait for mutex and grab it
-------------------------------------------------------------------------- */
            DbgStamp (DBG_SAP_FLOW);
            DbgPlain (DBG_SAP_FLOW, _T("I'll wait for Mutex and I'll grab it."));

            DbgStamp (DBG_SAP_STATUS);
            DbgPlain (DBG_SAP_STATUS,
                _T("[%s] Completing online backup\n"),
                __FCN__);

            if (WaitForSingleObject (hMutex, INFINITE) != WAIT_OBJECT_0)
            {
                DbgStamp (DBG_UNEXPECTED);
                DbgPlain (DBG_UNEXPECTED,
                    _T("[%s] WaitForSingleObject() failed. Error: %s"),
                    __FCN__,
                    ErhSysErrnoToText(GetLastError()));

                ErhFullReport (
                    __FCN__,
                    ERH_MAJOR,
                    NlsGetMessage(
                        NLS_SET_SAP,
                        NLS_CANNOT_WAITMUTEX,
                        GetLastError()) );

                mode = 1;

                break;
            }

            DbgPlain (DBG_SAP_FLOW,
                _T("[%s] Wait for mutex succeeded\n"),
                __FCN__);

/* ---------------------------------------------------------------------------
|        Create switchList file
 -------------------------------------------------------------------------- */

            DbgStamp (DBG_SAP_INFO);
            DbgPlain (DBG_SAP_INFO, _T("SWITCH list file is created with the following entries"));
            DbgPlain (DBG_SAP_INFO, SAP_END, path);

            if ((fpList = fopen(switchList, _T("w"))) == NULL)
            {
                DbgStamp (DBG_UNEXPECTED);
                DbgPlain (DBG_UNEXPECTED,
                   _T("[%s] fopen(switchList=%s, \"w\") failed. Error: %s"),
                    __FCN__,
                    switchList,
                    ErhSysErrnoToText(GetLastError()));

                ErhFullReport (
                    __FCN__,
                    ERH_CRITICAL,
                    NlsGetMessage(
                        NLS_SET_SAP,
                        NLS_CANNOT_OPEN_SWITCHLIST,
                        GetLastError()));

                mode = 1;

                break;
            }

            fprintf (fpList, SAP_END, path);
            fclose (fpList);

/* ---------------------------------------------------------------------------
|        Create switchSem file
 -------------------------------------------------------------------------- */
            DbgStamp (DBG_SAP_FLOW);
            DbgPlain (DBG_SAP_FLOW, _T("I'll create switchSem file."));

            if ((fpSem = fopen (switchSem, _T("w"))) == NULL)
            {
                DbgStamp (DBG_UNEXPECTED);
                DbgPlain (DBG_UNEXPECTED,
                    _T("[%s] fopen(switchSem=%s, \"w\") failed. Error: %s"),
                    __FCN__,
                    switchSem,
                    ErhSysErrnoToText(GetLastError()));

                ErhFullReport (
                    __FCN__,
                    ERH_CRITICAL,
                    NlsGetMessage(
                        NLS_SET_SAP,
                        NLS_CANNOT_OPEN_SEMLIST,
                        GetLastError()));

                mode = 1;

                break;
            }

            fprintf (fpSem, _T("\n"));
            fclose (fpSem);

/* ---------------------------------------------------------------------------
|        Wait until switchSem file is deleted
 -------------------------------------------------------------------------- */
            DbgStamp (DBG_SAP_FLOW);
            DbgPlain (DBG_SAP_FLOW,
                _T("[%s] Waiting until switchSem file is deleted...\n"),
                __FCN__);

            while (i++<=MAX_POLL_ITERATIONS)
            {
                sleep (POLL_SLEEP);
                if (OB2_StatFile(switchSem, NULL) == -1)
                {
                    DbgStamp (DBG_SAP_FLOW);
                    DbgPlain (DBG_SAP_FLOW, _T("INVALID_HANDLE_VALUE"));
                    break;
                }
            }

            DbgStamp (DBG_SAP_FLOW);
            DbgPlain (DBG_SAP_FLOW,
                _T("[%s] switchSem file is deleted (i=%d)\n"),
                __FCN__,
                i);

            state = STATE_UNDEF;

            DbgPlain (DBG_SAP_FLOW,
                _T("[%s] Waiting for brbackup"),
                __FCN__);

            if (i>MAX_POLL_ITERATIONS)
            {
                DbgStamp (DBG_UNEXPECTED);
                DbgPlain (DBG_UNEXPECTED,
                    _T("[%s] Error: Brbackup doesn't respond (i>%d). No Error."),
                    __FCN__, MAX_POLL_ITERATIONS);

                ErhFullReport (
                    __FCN__,
                    ERH_MAJOR,
                    NlsGetMessage(
                        NLS_SET_SAP,
                        NLS_BRBACKUP_HANG) );

                mode = 1;
            }
            else
            {
                tchar line[1024];

/* ---------------------------------------------------------------------------
|      Parsing switch log file
 -------------------------------------------------------------------------- */
                DbgStamp (DBG_SAP_FLOW);
                DbgPlain (DBG_SAP_FLOW,
                    _T("[%s] Brbackup responded"),
                    __FCN__);

                fpLog = fopen (switchLog, _T("r"));
                if (!fpLog)
                {
                    DbgStamp (DBG_UNEXPECTED);
                    DbgPlain (DBG_UNEXPECTED,
                        _T("[%s] fopen(switchLog=%s, \"r\") failed. Error: %s"),
                        __FCN__,
                        switchLog,
                        ErhSysErrnoToText(GetLastError()) );

                    ErhFullReport (
                        __FCN__,
                        ERH_CRITICAL,
                        NlsGetMessage(
                            NLS_SET_SAP,
                            NLS_CANNOT_OPEN_SWITCHLIST,
                            GetLastError()));

                    mode = 1;
                }

                while (fgets (line, 1024, fpLog))
                {
                    StripNewLine(line);
                    DbgPlain (DBG_SAP_INFO, _T("line: '%s'"), line);

                    if (strncmp (line, _T("#SUCCESS"), 8) == 0)
                    {
                        state = STATE_SUCCESS;
                        DbgPlain (DBG_SAP_INFO, _T("Matched #SUCCESS"));
                    }
                    else if (strncmp (line, _T("#ERROR"), 6) == 0)
                    {
                        state = STATE_ERROR;
                        DbgPlain (DBG_SAP_INFO, _T("Matched #ERROR"));
                    }
                    else
                    {
                        if (IsOutputNeeded(line))
                        {
                            printf (OUT_VERBOSE, line);
                        }
                    }
                }
                fclose (fpLog);

                DbgStamp (DBG_SAP_FLOW);
                DbgPlain (DBG_SAP_FLOW, _T("Deleting switchLog file."));

                if (DeleteFile (switchLog) == FALSE)
                {
                    int err = GetLastError();

                    DbgStamp (DBG_UNEXPECTED);
                    DbgPlain (DBG_UNEXPECTED,
                        _T("[%s] DeleteFile(switchLog=%s) failed. Error: %s"),
                        __FCN__,
                        switchLog,
                        ErhSysErrnoToText(GetLastError()));

                    ErhFullReport(
                        __FCN__,
                        ERH_MINOR,
                        NlsGetMessage(
                            NLS_SET_SAP,
                            NLS_SAP_DELETE_FAILED,
                            switchLog,
                            ErhSysErrnoToText(err)));

                    mode = 1;
                }

            }
/* ---------------------------------------------------------------------------
|      Release mutex
 -------------------------------------------------------------------------- */

            DbgStamp (DBG_SAP_FLOW);
            DbgPlain (DBG_SAP_FLOW, _T("### Now I will release mutex!!"));

            if (ReleaseMutex (hMutex) == FALSE)
            {
                DbgStamp (DBG_UNEXPECTED);
                DbgPlain (DBG_UNEXPECTED,
                    _T("%s: ReleaseMutex() failed. Error: %s"),
                    __FCN__,
                    ErhSysErrnoToText(GetLastError()));

                ErhFullReport (
                    __FCN__,
                    ERH_CRITICAL,
                    NlsGetMessage(
                        NLS_SET_SAP,
                        NLS_CANNOT_RELEASE_MUTEX,
                        GetLastError()) );

                mode = 1;

                break;
            }

            DbgStamp(DBG_SAP_FLOW);
            DbgPlain (DBG_SAP_FLOW, _T("[%s] Mutex released\n"), __FCN__);
            if (state != STATE_SUCCESS)
            {
                break;
            }
        }
    }

/* ---------------------------------------------------------------------------
|    ... and close current backup object
 -------------------------------------------------------------------------- */
    DbgStamp (DBG_SAP_FLOW);
    DbgPlain (DBG_SAP_FLOW,
        _T("[%s] Calling OB2_EndObjectBackup(context,%d)\n"),
        __FCN__,
        mode ? mode : OB2_GetErrno(context));

    if (OB2_EndObjectBackup(context, mode ? mode : OB2_GetErrno(context)))
    {
        ERR ( NlsGetMessage (
                             NLS_SET_SAP,
                                 NLS_SAP_CANNOT_COMPLETE_BACKUP_SET),
                                 context);
    }

EndBackEXIT:
    OB2_EndBackup(context, mode ? mode : OB2_GetErrno(context));

EXIT:
    if (!mode)
    {
        mode = OB2_GetErrno(context);
    }

    OB2_Exit (context);

    fclose (inFile);

    DbgFcnOut();
    ExitProcess (mode);
}

