

#should be absolute path
codegenerator_root=`pwd`

generated_source_path="$codegenerator_root/src"
cache_config_file_path="$generated_source_path/distributed_cache_configuration.xml"
cache_entity_mapping_config_file_path="$generated_source_path/cache_entity_mapping.xml"

#can have relative paths(with respective to working directory)
class_path="/home/prashanth/FMS/8.2/ROC_FM_Spark/server-modular/deploy/lib/protostream-2.0.2.Final.jar:."
source_path="$codegenerator_root/resources/codegenerator-resources.jar:."

compiled_classes_dir="$codegenerator_root/classes"

deploy_contents_dir="$generated_source_path/deploy_contents"
deploy_dir="$codegenerator_root/deploy"
data_components_jar_file_path="$deploy_dir/distributedcache-data-components-autogenerated.jar"
#final deliverable
data_components_tar_file_path="$deploy_dir/distributedcache-data-components-autogenerated.tar"

required_dir_paths="$generated_source_path $compiled_classes_dir $deploy_contents_dir/lib $deploy_contents_dir/config $deploy_dir"

for dir_path in $required_dir_paths
do
	if ! ( test -d $dir_path )
	then
		mkdir -p $dir_path
	fi
done


#----
#placeholder for source code generation executable
#----

old_pwd=`pwd`
cd src
javac -classpath $class_path -sourcepath $source_path -d $compiled_classes_dir @generated_java_files.fls
cd $old_pwd
echo "Compilation has been completed successfully. Creating the jar file . . ."
jar -cvf $data_components_jar_file_path -C $compiled_classes_dir . 

old_pwd=`pwd`
cd src
jar -uvf $data_components_jar_file_path @generated_resource_files.fls
cd $old_pwd

echo "Created the jar file at $data_components_jar_file_path"

echo "Copying deployable contents into $deploy_contents_dir"

cp $data_components_jar_file_path $deploy_contents_dir/lib 
cp $cache_config_file_path $deploy_contents_dir/config
cp $cache_entity_mapping_config_file_path $deploy_contents_dir/config

echo "Packaging deployable contents . . ."

old_pwd=`pwd`
cd $deploy_contents_dir
tar -cvf $data_components_tar_file_path lib  config 
cd $old_pwd

echo "Created $data_components_tar_file_path"

echo "Code generation has been completed successfully. Final deliverable is available at [$data_components_tar_file_path]"
