#!/bin/bash

 $1 << EOF

DROP VIEW BASIC_FILTER_CONFIG_V ;
CREATE OR REPLACE VIEW BASIC_FILTER_CONFIG_V 
AS SELECT * FROM 
( 
		SELECT
            FIELD_CONFIGS.ID, FIELD_CONFIGS.NAME, FIELD_CONFIGS.RECORD_CONFIG_ID, FIELD_CONFIGS.FIELD_ID,
            FIELD_CONFIGS.DATA_TYPE, DECODE(BASIC_FILTER_CONFIGS.TRANSLATION_ID, NULL,
                FIELD_CONFIGS.TRANSLATION_ID,BASIC_FILTER_CONFIGS.TRANSLATION_ID) AS TRANSLATION_ID,
            REGULAR_EXPRESSIONS.EXPRESSION REG_EX, BASIC_FILTER_CONFIGS.OPERATOR_ID,
            BASIC_FILTER_CONFIGS.IS_MANDATORY, BASIC_FILTER_CONFIGS.MIN,
            BASIC_FILTER_CONFIGS.MAX, BASIC_FILTER_CONFIGS.RECORD_VIEW_CONFIG_ID
            FROM FIELD_CONFIGS, BASIC_FILTER_CONFIGS, REGULAR_EXPRESSIONS
            WHERE FIELD_CONFIGS.RECORD_CONFIG_ID = BASIC_FILTER_CONFIGS.RECORD_CONFIG_ID
            AND FIELD_CONFIGS.FIELD_ID = BASIC_FILTER_CONFIGS.FIELD_ID
            AND NVL(FIELD_CONFIGS.REG_EXP_ID,0) = REGULAR_EXPRESSIONS.ID
            ORDER BY BASIC_FILTER_CONFIGS.POSITION
);

EOF
