#!/bin/bash

sqlplus $1 << EOF

CREATE OR REPLACE VIEW SCHEDULED_REPORTS_V AS
(
 SELECT
 S.ID AS ID ,substr(S.JOB_NAME,0,instr(S.JOB_NAME,'-')-2) AS REPORT_NAME ,substr(S.JOB_NAME,instr(S.JOB_NAME,'-')+2) AS USER_NAME,
 S.PROCESS_TIME AS PROCESS_TIME,DECODE(S.HOURLY, '-1', '', HOURLY) AS HOURLY,
 DECODE(S.MINUTE, '-1', '',MINUTE) AS MINUTE, S.DAY_OF_WEEK AS DAY_OF_WEEK, DECODE(S.DAY_OF_MONTH,'-1','',DAY_OF_MONTH) AS DAY_OF_MONTH,
 DECODE(S.MONTH_OF_YEAR,'-1',0,MONTH_OF_YEAR) AS MONTH_OF_YEAR, S.PARAMETER AS PARAMETER,JOINMANYROWSIN1UNIQ(N.id) AS NETWORK
 FROM
 SCHEDULERS S, NETWORKS N, NETWORKS_SCHEDULERS NS
 WHERE
 S.ID = NS.SCHEDULER_ID AND NS.NETWORK_ID = N.ID AND S.CATEGORY='REPORT_SCHEDULE'
 GROUP BY
 S.ID, S.JOB_NAME, S.PROCESS_TIME, S.SCHEDULE_TYPE, S.HOURLY, S.MINUTE, S.DAY_OF_WEEK,
 S.DAY_OF_MONTH, S.MONTH_OF_YEAR, S.PARAMETER
 );

EOF
