#!/bin/bash

 $1 << EOF

DROP VIEW rules_V ;
CREATE OR REPLACE VIEW RULES_V AS
(
		SELECT R.ID AS ID, R.NAME AS NAME, R.KEY AS KEY,
		R.PSEUDO_FUNCTION_ID AS FUNCTION, R.AGGREGATION_TYPE AS AGGREGATION_TYPE
		FROM RULES R
) ;
/
commit ;

EOF
