sqlplus $1 << EOF

DROP VIEW SUBSCRIBER_NEURAL_PROFILE;

CREATE OR REPLACE VIEW SUBSCRIBER_NEURAL_PROFILE
AS
(SELECT * FROM SUBSCR_NEURAL_DATA_PROFILE UNION ALL SELECT * FROM SUBSCR_NEURAL_VOICE_PROFILE) ;

EOF
