#!/bin/bash

 $1 << EOF

DROP VIEW RTF_ENTITY_GROUPS_V ;

CREATE OR REPLACE VIEW RTF_ENTITY_GROUPS_V AS
(
    SELECT SGP.ID, SGP.KEY AS NAME, SGP.RECORD_CONFIG_ID AS ENTITY_TYPE, 1 AS DATASET_TYPE
    FROM SUBSCRIBER_GROUPS SGP
    UNION ALL
    SELECT ID, NAME ,ENTITY_TYPE, DATASET_TYPE FROM RTF_ENTITY_GROUPS
) ;

EOF
