#! /bin/bash

. $WATIR_SERVER_HOME/Scripts/configuration.sh
. $COMMON_MOUNT_POINT/Conf/rangerenv.sh


GenerateDBCEFile ()
{
	echo "Generating $WATIR_SERVER_HOME/Scripts/$dbce_sql_file_name file..."

	echo "-----------------------------------------------------------------------------------------------------------------" >>$WATIR_SERVER_HOME/Scripts/$dbce_sql_file_name
    echo "----    This file is Generated by createBackupTables.sh which is called from set_fixture_enviorment.         ----" >>$WATIR_SERVER_HOME/Scripts/$dbce_sql_file_name
    echo "----    This script copies backupdata to default tables and modifies the sequences so as to be the same      ----" >>$WATIR_SERVER_HOME/Scripts/$dbce_sql_file_name
    echo "----    as after fixture.                                                                                    ----" >>$WATIR_SERVER_HOME/Scripts/$dbce_sql_file_name
    echo "-----------------------------------------------------------------------------------------------------------------" >>$WATIR_SERVER_HOME/Scripts/$dbce_sql_file_name
	echo "SPOOL $WATIR_SERVER_HOME/Scripts/dbce_sql_file_name ;" >> $WATIR_SERVER_HOME/Scripts/$dbce_sql_file_name
	echo "SET FEEDBACK ON ;" >> $WATIR_SERVER_HOME/Scripts/$dbce_sql_file_name
	echo "SET SERVEROUTPUT ON ;" >> $WATIR_SERVER_HOME/Scripts/$dbce_sql_file_name

    generateSequenceSection

    echo "commit ;">>$WATIR_SERVER_HOME/Scripts/$dbce_sql_file_name
	echo "SPOOL OFF ;">>$WATIR_SERVER_HOME/Scripts/$dbce_sql_file_name
	echo "exit ;">>$WATIR_SERVER_HOME/Scripts/$dbce_sql_file_name
	return 0
}

generateSequenceSection()
{
    getSequenceNames;
	lines=`cat $WATIR_SERVER_HOME/Scripts/sequenceNames.txt | wc -l`
	for (( i=1 ; i<=lines ; i=$i+2 ))
	do
		startValueLineno=`expr $i + 1`
		sequenceName=`cat $WATIR_SERVER_HOME/Scripts/sequenceNames.txt | head -$i | tail -1`
		sequenceStartValue=`cat $WATIR_SERVER_HOME/Scripts/sequenceNames.txt | head -$startValueLineno | tail -1`
		echo "DROP SEQUENCE $sequenceName ;">>$WATIR_SERVER_HOME/Scripts/$dbce_sql_file_name
echo "CREATE SEQUENCE $sequenceName INCREMENT BY 1 START WITH $sequenceStartValue NOMAXVALUE MINVALUE 1 NOCYCLE CACHE 20 ORDER ;" >>$WATIR_SERVER_HOME/Scripts/$dbce_sql_file_name
	done

return 0
}

# in this function we fetch the sequence name and it's start value incremented by 100 times the number of fixture
getSequenceNames()
{
	cat $WATIR_SERVER_HOME/Scripts/dbcecreatebacktables.sh | grep -i "CREATE SEQUENCE" | awk {'print $4 "\n" ($10+(SequenceIncrementPerFixture * fixtureNumber))'} SequenceIncrementPerFixture="$SequenceIncrementPerFixture" fixtureNumber="$fixtureNumber" >>$WATIR_SERVER_HOME/Scripts/sequenceNames.txt
	return 0
}



main ()
{
    if [ $# -eq 3 ]
    then
        dbce_sql_file_name=$1
	fixtureNumber=$2
	SequenceIncrementPerFixture=$3

    else
        echo "Improper Usage: Three arguments required 1:dbce_sql_file_name 2:fixtureNumber 3:SequenceIncrementPerFixture"
        exit 2
    fi

	rm -f $WATIR_SERVER_HOME/Scripts/$dbce_sql_file_name
   	rm -f $WATIR_SERVER_HOME/Scripts/sequenceNames.txt
	
	GenerateDBCEFile
}

main $*
