 $1 << EOF

DROP VIEW ACTIVE_SUB_GROUPS_V ;
CREATE OR REPLACE VIEW ACTIVE_SUB_GROUPS_V as
(
    SELECT SG.ID as ID,SG.KEY as KEY, SG.DESCRIPTION as DESCRIPTION, SG.PRIORITY as PRIORITY, SG.RECORD_CONFIG_ID as
    RECORD_CONFIG_ID ,N.ID as NETWORKS
    FROM SUBSCRIBER_GROUPS SG, NETWORKS N
    WHERE N.ID IN ( SELECT NETWORK_ID FROM NETWORKS_SUBSCRIBER_GROUPS WHERE SUBSCRIBER_GROUP_ID = SG.ID)
    AND SG.RECORD_CONFIG_ID = 3
) ;

EOF

