#!/bin/bash

 $1 << EOF

CREATE OR REPLACE VIEW STANDARD_NICKNAMES_V AS (
SELECT LST_CNFG.ID,LST_CNFG.DESCRIPTION, LST_CNFG.NAME, LST_CNFG.LIST_TYPE, LST_CNFG.FIELD_CATEGORY_ID, LST_CNFG.CATEGORY, JOINMANYROWSIN1(LST_CNFGS_NETWS.NETWORK_ID) "NETWORK_ID" FROM LIST_CONFIGS LST_CNFG, LIST_CONFIGS_NETWORKS LST_CNFGS_NETWS WHERE LST_CNFG.ID= LST_CNFGS_NETWS.LIST_CONFIG_ID AND LST_CNFG.NAME IS NOT NULL GROUP BY LST_CNFG.ID,LST_CNFG.NAME,LST_CNFG.LIST_TYPE,LST_CNFG.FIELD_CATEGORY_ID,LST_CNFG.CATEGORY, LST_CNFG.DESCRIPTION
);


commit ;
EOF
