#!/bin/bash

 $1 << EOF

CREATE OR REPLACE VIEW FP_ELEMENTS_V AS
(
	SELECT FE.ID, FE.NAME, FE.DESCRIPTION, FE.ENTITY_ID, FE.ELEMENT_TYPE, FE.RECORD_CONFIG_ID, FE.FIELD_ID, FC.NAME AS ELEMENT_NAME,
		FE.RULE_KEY, R.PSEUDO_FUNCTION_ID AS FUNCTION, ROUND(T.DURATION / 86400, 6) AS TIME_WINDOW,
		DECODE(R.IS_ENABLED, 0, 'Disabled', 1, 'Enabled') AS STATUS, nvl(FE.SERVICE_NUMBER_TYPE,0) AS SERVICE_NUMBER_TYPE,
		R.CATEGORY AS RULE_CATEGORY
	FROM FP_ELEMENTS FE, FIELD_CONFIGS FC, RULES R, THRESHOLDS T
	WHERE FE.FIELD_ID = FC.FIELD_ID AND FE.RECORD_CONFIG_ID = FC.RECORD_CONFIG_ID AND FE.FIELD_ID IS NOT NULL AND FE.IS_ACTIVE = 1
		AND FE.RULE_KEY = R.KEY AND R.IS_ACTIVE =1 AND T.RULE_KEY = R.KEY AND T.RULE_VERSION = R.VERSION
		AND T.THRESHOLD_ID=0 AND T.AGGREGATION_VALUE IS NULL
	UNION ALL
	SELECT FE.ID, FE.NAME, FE.DESCRIPTION, FE.ENTITY_ID, FE.ELEMENT_TYPE, FE.RECORD_CONFIG_ID, FE.FIELD_ID,  ' ' AS ELEMENT_NAME,
		FE.RULE_KEY, R.PSEUDO_FUNCTION_ID AS FUNCTION, ROUND(T.DURATION / 86400, 6) AS TIME_WINDOW,
		DECODE(R.IS_ENABLED, 0, 'Disabled', 1, 'Enabled') AS STATUS, nvl(FE.SERVICE_NUMBER_TYPE,0) AS SERVICE_NUMBER_TYPE,
		R.CATEGORY AS RULE_CATEGORY
	FROM FP_ELEMENTS FE, RULES R, THRESHOLDS T
	WHERE FE.FIELD_ID IS NULL AND FE.IS_ACTIVE = 1
		AND FE.RULE_KEY = R.KEY AND R.IS_ACTIVE = 1 AND T.RULE_KEY = R.KEY  AND T.RULE_VERSION = R.VERSION
		AND T.THRESHOLD_ID=0 AND T.AGGREGATION_VALUE IS NULL
);


CREATE OR REPLACE VIEW FP_PROFILES_MAP_V AS
(
    SELECT * FROM FP_SUSPECT_PROFILES_16
    UNION ALL
    SELECT * FROM FP_SUSPECT_PROFILES_214
    UNION ALL
    SELECT * FROM FP_PROFILES_16_1
    UNION ALL
    SELECT * FROM FP_PROFILES_214_1
    UNION ALL
    SELECT * FROM fp_profiles_16_0_2
    UNION ALL
    SELECT * FROM fp_profiles_214_0_2
);

CREATE OR REPLACE VIEW FP_MATCH_TYPE_0_V AS
(
    SELECT * FROM FP_PROFILES_16_1
    UNION ALL
    SELECT * FROM FP_PROFILES_214_1
    UNION ALL
    SELECT * FROM fp_profiles_16_0_2
    UNION ALL
    SELECT * FROM fp_profiles_214_0_2
);

CREATE OR REPLACE VIEW FP_MATCH_TYPE_0_16_V AS
(
    SELECT * FROM FP_PROFILES_16_1
    UNION ALL
    SELECT * FROM fp_profiles_16_0_2
);

CREATE OR REPLACE VIEW FP_MATCH_TYPE_0_214_V AS
(
    SELECT * FROM FP_PROFILES_214_1
    UNION ALL
    SELECT * FROM fp_profiles_214_0_2
);

CREATE OR REPLACE VIEW FP_ENTITYID_16_V AS
(
    SELECT * FROM FP_PROFILES_16_1
    UNION ALL
    SELECT * FROM FP_SUSPECT_PROFILES_16
    UNION ALL
    SELECT * FROM fp_profiles_16_0_2
);

CREATE OR REPLACE VIEW FP_ENTITYID_214_V AS
(
    SELECT * FROM FP_PROFILES_214_1
    UNION ALL
    SELECT * FROM FP_SUSPECT_PROFILES_214
    UNION ALL
    SELECT * FROM fp_profiles_214_0_2
);

CREATE OR REPLACE VIEW FP_MATCH_TYPE_1_V AS
(
    SELECT * FROM FP_SUSPECT_PROFILES_16
    UNION ALL
    SELECT * FROM FP_SUSPECT_PROFILES_214
);
EOF
