#!/bin/bash

 $1 << EOF

CREATE OR REPLACE VIEW STATRULES_V
AS
(
	SELECT PF.ID, PF.NAME, PF.DESCRIPTION, PF.ENTITY_ID, PF.RECORD_CONFIG_ID, PF.TIME_WINDOW, PF.RULE_KEY, PF.ELEMENT_TYPE,
		R.PSEUDO_FUNCTION_ID AS FUNCTION, R.VERSION, DECODE(R.IS_ENABLED, 0, 'Disabled', 1, 'Enabled') AS STATUS
	FROM FP_ELEMENTS PF, RULES R
	WHERE PF.RULE_KEY = R.KEY AND R.IS_ACTIVE = 1
);


EOF
