#/*******************************************************************************
# *	Copyright (c) Subex Azure Limited 2006. All rights reserved.	           *
# *	The copyright to the computer program(s) herein is the property of Subex   *
# *	Azure Limited. The program(s) may be used and/or copied with the written *
# *	permission from Subex Azure Limited or in accordance with the terms and  *
# *	conditions stipulated in the agreement/contract under which the program(s) *
# *	have been supplied.                                                        *
# *******************************************************************************/

#!/bin/bash

 $1 << EOF
SET FEEDBACK OFF;

DROP TABLE PARTITION_TBL ;
CREATE TABLE PARTITION_TBL (
	PTN_ID             NUMBER(10) NOT NULL,
 	PTN_NAME           NVARCHAR2(255) NOT NULL,
 	PTN_DELETE_FL      CHAR(1) NOT NULL,
 	PTN_VERSION_ID     NUMBER(10) NOT NULL) ;

INSERT INTO PARTITION_TBL (PTN_ID, PTN_NAME, PTN_DELETE_FL, PTN_VERSION_ID) VALUES (2, 'IT', 'N', 1) ;
INSERT INTO PARTITION_TBL (PTN_ID, PTN_NAME, PTN_DELETE_FL, PTN_VERSION_ID) VALUES (3, 'Business', 'N', 1) ;
INSERT INTO PARTITION_TBL (PTN_ID, PTN_NAME, PTN_DELETE_FL, PTN_VERSION_ID) VALUES (4, 'Executive', 'N', 1) ;

CREATE OR REPLACE VIEW DASHBOARD_PARTITION_TASK_MAP AS SELECT P.PTN_ID PARTITION_ID, T.ID TASK_ID FROM PARTITION_TBL P, TASKS T WHERE T.IMAGE_SRC = P.PTN_NAME ;

DROP TABLE USER_TBL ;

CREATE TABLE USER_TBL (
	USR_ID             NUMBER(10) NOT NULL,
	PIG_ID             NUMBER(10) NOT NULL,
	USR_NAME           NVARCHAR2(255) NOT NULL,
	USR_PASSWORD       NVARCHAR2(255) NOT NULL,
	USR_FORENAME       NVARCHAR2(255) NOT NULL,
	USR_SURNAME        NVARCHAR2(255) NOT NULL,
	USR_EMAIL_ADDRESS  NVARCHAR2(255) NOT NULL,
	USR_DISABLED_FL    CHAR(1) NOT NULL,
	USR_DELETE_FL      CHAR(1) NOT NULL,
	USR_VERSION_ID     NUMBER(10) NOT NULL,
	PTN_ID             NUMBER(10) NOT NULL) ; 

INSERT INTO USER_TBL (USR_ID, PIG_ID, USR_NAME, USR_PASSWORD, USR_FORENAME, USR_SURNAME, USR_EMAIL_ADDRESS, USR_DISABLED_FL, USR_DELETE_FL, USR_VERSION_ID, PTN_ID) VALUES (1, 1, 'radmin', 'PASS_ME', 'A', 'B', 'C', 'N', 'N', 1, 1) ;
INSERT INTO USER_TBL (USR_ID, PIG_ID, USR_NAME, USR_PASSWORD, USR_FORENAME, USR_SURNAME, USR_EMAIL_ADDRESS, USR_DISABLED_FL, USR_DELETE_FL, USR_VERSION_ID, PTN_ID) VALUES (2, 2, 'default', 'PASS_ME', 'A', 'B', 'C', 'N', 'N', 1, 1) ;
INSERT INTO USER_TBL (USR_ID, PIG_ID, USR_NAME, USR_PASSWORD, USR_FORENAME, USR_SURNAME, USR_EMAIL_ADDRESS, USR_DISABLED_FL, USR_DELETE_FL, USR_VERSION_ID, PTN_ID) VALUES (3, 3, 'anderson', 'PASS_ME', 'A', 'B', 'C', 'N', 'N', 1, 1) ;
INSERT INTO USER_TBL (USR_ID, PIG_ID, USR_NAME, USR_PASSWORD, USR_FORENAME, USR_SURNAME, USR_EMAIL_ADDRESS, USR_DISABLED_FL,
USR_DELETE_FL, USR_VERSION_ID, PTN_ID) VALUES (4, 4, 'anderson1', 'PASS_ME', 'A', 'B', 'C', 'N', 'N', 1, 1) ;

DROP TABLE ROLE_TBL ;

CREATE TABLE ROLE_TBL (
	ROL_ID             NUMBER(10) NOT NULL,
	ROL_NAME           NVARCHAR2(255) NOT NULL,
	ROL_DELETE_FL      CHAR(1) NOT NULL,
	ROL_VERSION_ID     NUMBER(10) NOT NULL,
	PTN_ID             NUMBER(10) NOT NULL) ;

INSERT INTO ROLE_TBL (ROL_ID, ROL_NAME, ROL_DELETE_FL, ROL_VERSION_ID, PTN_ID) VALUES (1, 'Create', 'N', 1, 1) ;
INSERT INTO ROLE_TBL (ROL_ID, ROL_NAME, ROL_DELETE_FL, ROL_VERSION_ID, PTN_ID) VALUES (2, 'View', 'N', 1, 1) ;

CREATE OR REPLACE PACKAGE DB_USER
AS
  TYPE TMP_PARTITION_TBL IS TABLE OF NUMBER(20) INDEX BY INTEGER ;
  PROCEDURE CREATE_USER(USER_NAME IN VARCHAR2, ROLE_ID IN NUMBER, PARTITION_IDS IN TMP_PARTITION_TBL) ;
  PROCEDURE DELETE_USER(USER_NAME IN VARCHAR2) ;
  PROCEDURE UPDATE_USER_ROLE_PARTITION(USER_NAME IN VARCHAR2, ROLE_ID IN NUMBER, PARTITION_IDS IN TMP_PARTITION_TBL) ;
END DB_USER ;
/

CREATE OR REPLACE PACKAGE BODY DB_USER
AS
  PROCEDURE CREATE_USER(USER_NAME IN VARCHAR2, ROLE_ID IN NUMBER, PARTITION_IDS IN TMP_PARTITION_TBL)
  IS
  BEGIN
	INSERT INTO USER_TBL (USR_ID, PIG_ID, USR_NAME, USR_PASSWORD, USR_FORENAME, USR_SURNAME, USR_EMAIL_ADDRESS, USR_DISABLED_FL, USR_DELETE_FL, USR_VERSION_ID, PTN_ID) VALUES (999, 1, USER_NAME, 'PASS_ME', 'A', 'B', 'C', 'N', 'N', 1, 1) ;
	insert into configurations (ID, CONFIG_KEY, VALUE, IS_VISIBLE) VALUES (1234, 'DASHBOARD_USER_CREATED_'||USER_NAME||'_'||ROLE_ID, 'created', 1);
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK ;
  END CREATE_USER ;
  PROCEDURE UPDATE_USER_ROLE_PARTITION(USER_NAME IN VARCHAR2, ROLE_ID IN NUMBER, PARTITION_IDS IN TMP_PARTITION_TBL)
  IS
  BEGIN
	insert into configurations (ID, CONFIG_KEY, VALUE, IS_VISIBLE) VALUES (1235, 'DASHBOARD_USER_UPDATED_'||USER_NAME||'_'||ROLE_ID, 'updated', 1) ;
  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(SQLERRM) ;
      ROLLBACK;
  END UPDATE_USER_ROLE_PARTITION ;
  PROCEDURE DELETE_USER(USER_NAME IN VARCHAR2)
  IS
  BEGIN
	insert into configurations (ID, CONFIG_KEY, VALUE, IS_VISIBLE) VALUES (1235, 'DASHBOARD_USER_DELETED_'||USER_NAME, 'deleted', 1) ;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
  END DELETE_USER ;
END DB_USER ;
/

commit ;
EOF

