#! /bin/bash

. $RANGERHOME/sbin/rangerenv.sh

generateUniqueSequenceNames()
{
	cat $DBSETUP_HOME/*.sql | grep -i "CREATE SEQUENCE" >$RUBY_UNIT_HOME/Scripts/Fixture/tmp/allSequenceCreationList.txt

	tr '[:lower:]' '[:upper:]'<$RUBY_UNIT_HOME/Scripts/Fixture/tmp/allSequenceCreationList.txt >$RUBY_UNIT_HOME/Scripts/Fixture/tmp/allSequenceCreationListUpperCase.txt
	awk {'print $3'}<$RUBY_UNIT_HOME/Scripts/Fixture/tmp/allSequenceCreationListUpperCase.txt >$RUBY_UNIT_HOME/Scripts/Fixture/tmp/allSequenceNames.txt
	
	awk '{
		if ($0 in stored_lines)
		x=1
	    else
		print
		stored_lines[$0]=1
	     }' $RUBY_UNIT_HOME/Scripts/Fixture/tmp/allSequenceNames.txt > $RUBY_UNIT_HOME/Scripts/uniqueSequenceNames.txt

return 0
}

getFileHeader()
{
echo "-----------------------------------------------------------------------------------------------------------------" >> $RUBY_UNIT_HOME/Scripts/$dbce_sql_file_name
        echo "--This file is Generated by generateEntireSequenceCreationList.sh which is called from CEInit.sh " >> $RUBY_UNIT_HOME/Scripts/$dbce_sql_file_name
        echo "--The script generates necessary sequences and should not be deleted" >> $RUBY_UNIT_HOME/Scripts/$dbce_sql_file_name
        echo "-----------------------------------------------------------------------------------------------------------------" >> $RUBY_UNIT_HOME/Scripts/$dbce_sql_file_name
        echo "SPOOL \$RUBY_UNIT_HOME/Scripts/Fixture/tmp/$spoolFileName ;" >> $RUBY_UNIT_HOME/Scripts/$dbce_sql_file_name
        echo "SET FEEDBACK ON ;" >> $RUBY_UNIT_HOME/Scripts/$dbce_sql_file_name
        echo "SET SERVEROUTPUT ON ;" >> $RUBY_UNIT_HOME/Scripts/$dbce_sql_file_name

return 0
}

getFileTail()
{
        echo "commit ;" >> $RUBY_UNIT_HOME/Scripts/$dbce_sql_file_name
	echo "SPOOL \$RUBY_UNIT_HOME/Scripts/Fixture/tmp/sequenceFlag.lst ;">> $RUBY_UNIT_HOME/Scripts/$dbce_sql_file_name
        echo "SPOOL OFF ;" >> $RUBY_UNIT_HOME/Scripts/$dbce_sql_file_name
        echo "exit ;"   >> $RUBY_UNIT_HOME/Scripts/$dbce_sql_file_name


return 0
}

generateSequences()
{
	incrementFactor=`expr $fixtureNumber \* $sequenceIncrementPerFixture`
	sequenceStartValue=`expr $defaultSequenceStartValue + $incrementFactor`

	getFileHeader

for i in `cat $RUBY_UNIT_HOME/Scripts/uniqueSequenceNames.txt`
do
        sequenceName=$i

	echo "DROP SEQUENCE $sequenceName ;">>$RUBY_UNIT_HOME/Scripts/$dbce_sql_file_name
        echo "CREATE SEQUENCE $sequenceName INCREMENT BY 1 START WITH $sequenceStartValue NOMAXVALUE MINVALUE 4000 NOCYCLE CACHE 20 ORDER ;" >>$RUBY_UNIT_HOME/Scripts/$dbce_sql_file_name
done

	getFileTail

return 0
}


main()
{
if [ $# -eq 0 ]
then
	fixtureNumber=0
	sequenceIncrementPerFixture=0
	dbce_sql_file_name="dbce.sql"
elif [ $# -eq 2 ]
then
	fixtureNumber=$1
	sequenceIncrementPerFixture=$2
	dbce_sql_file_name="dbceFixtureLevel$fixtureNumber.sql"
else
	echo "Improper usage: Zero or Two parameters required"
	echo "		Zero Parameters: dbce.sql will be generated"
	echo "		Two Parameters: 1:fixtureNumber 2:sequenceIncrementPerFixture"
	exit 2
fi

	rm -f $RUBY_UNIT_HOME/Scripts/uniqueSequenceNames.txt
	rm -f $RUBY_UNIT_HOME/Scripts/$dbce_sql_file_name

	defaultSequenceStartValue=4000
	spoolFileName="$dbce_sql_file_name.lst"
	
	echo "Generating file $RUBY_UNIT_HOME/Scripts/$dbce_sql_file_name ..."
	generateUniqueSequenceNames
	generateSequences

}

main $*
