
CREATE TABLE HP_SUMMARY_DATE_MIGRATE
(
 	HPP_MSISDN		   VARCHAR2(25) NOT NULL,
	HPP_IMSI		   VARCHAR2(20) NOT NULL,
	HPP_IMEI		   VARCHAR2(20) NOT NULL,
	HPP_DAYS		   NUMBER(10)   NOT NULL
) 
PARTITION BY HASH(HPP_MSISDN,HPP_IMEI,HPP_IMSI)
(
	PARTITION P001 TABLESPACE TS_HP_SMR_DATE001, 
	PARTITION P002 TABLESPACE TS_HP_SMR_DATE002,
	PARTITION P003 TABLESPACE TS_HP_SMR_DATE003,
	PARTITION P004 TABLESPACE TS_HP_SMR_DATE004,
	PARTITION P005 TABLESPACE TS_HP_SMR_DATE005,
	PARTITION P006 TABLESPACE TS_HP_SMR_DATE006,
	PARTITION P007 TABLESPACE TS_HP_SMR_DATE007,
	PARTITION P008 TABLESPACE TS_HP_SMR_DATE008,
	PARTITION P009 TABLESPACE TS_HP_SMR_DATE009, 
	PARTITION P010 TABLESPACE TS_HP_SMR_DATE010,
	PARTITION P011 TABLESPACE TS_HP_SMR_DATE011,
	PARTITION P012 TABLESPACE TS_HP_SMR_DATE012,
	PARTITION P013 TABLESPACE TS_HP_SMR_DATE013,
	PARTITION P014 TABLESPACE TS_HP_SMR_DATE014,
	PARTITION P015 TABLESPACE TS_HP_SMR_DATE015,
	PARTITION P016 TABLESPACE TS_HP_SMR_DATE016
	PARTITION P017 TABLESPACE TS_HP_SMR_DATE017, 
	PARTITION P018 TABLESPACE TS_HP_SMR_DATE018,
	PARTITION P019 TABLESPACE TS_HP_SMR_DATE019,
	PARTITION P020 TABLESPACE TS_HP_SMR_DATE020,
	PARTITION P021 TABLESPACE TS_HP_SMR_DATE021,
	PARTITION P022 TABLESPACE TS_HP_SMR_DATE022,
	PARTITION P023 TABLESPACE TS_HP_SMR_DATE023,
	PARTITION P024 TABLESPACE TS_HP_SMR_DATE024
	PARTITION P025 TABLESPACE TS_HP_SMR_DATE025, 
	PARTITION P026 TABLESPACE TS_HP_SMR_DATE026,
	PARTITION P027 TABLESPACE TS_HP_SMR_DATE027,
	PARTITION P028 TABLESPACE TS_HP_SMR_DATE028,
	PARTITION P029 TABLESPACE TS_HP_SMR_DATE029,
	PARTITION P030 TABLESPACE TS_HP_SMR_DATE030,
	PARTITION P031 TABLESPACE TS_HP_SMR_DATE031,
	PARTITION P032 TABLESPACE TS_HP_SMR_DATE032
) ;


				

  CREATE INDEX "RANGER"."IX_HP_SUM_DATE_PH_IME_IMS_MIG" ON "RANGER"."HP_SUMMARY_DATE_MIGRATE" ("HPP_MSISDN", "HPP_IMEI", "HPP_IMSI")
  PCTFREE 10 INITRANS 2 MAXTRANS 255  NOLOGGING
  STORAGE(
  BUFFER_POOL DEFAULT) LOCAL
 (PARTITION "P001"
   TABLESPACE "TS_HP_SMR_DATE001",
 PARTITION "P002"
   TABLESPACE "TS_HP_SMR_DATE002",
 PARTITION "P003"
   TABLESPACE "TS_HP_SMR_DATE003",
 PARTITION "P004"
   TABLESPACE "TS_HP_SMR_DATE004",
 PARTITION "P005"
   TABLESPACE "TS_HP_SMR_DATE005",
 PARTITION "P006"
   TABLESPACE "TS_HP_SMR_DATE006",
 PARTITION "P007"
   TABLESPACE "TS_HP_SMR_DATE007",
 PARTITION "P008"
   TABLESPACE "TS_HP_SMR_DATE008",
 PARTITION "P009"
   TABLESPACE "TS_HP_SMR_DATE009",
 PARTITION "P010"
   TABLESPACE "TS_HP_SMR_DATE010",
 PARTITION "P011"
   TABLESPACE "TS_HP_SMR_DATE011",
 PARTITION "P012"
   TABLESPACE "TS_HP_SMR_DATE012",
 PARTITION "P013"
   TABLESPACE "TS_HP_SMR_DATE013",
 PARTITION "P014"
   TABLESPACE "TS_HP_SMR_DATE014",
 PARTITION "P015"
   TABLESPACE "TS_HP_SMR_DATE015",
 PARTITION "P016"
   TABLESPACE "TS_HP_SMR_DATE016",
 PARTITION "P017"
   TABLESPACE "TS_HP_SMR_DATE017",
 PARTITION "P018"
   TABLESPACE "TS_HP_SMR_DATE018",
 PARTITION "P019"
   TABLESPACE "TS_HP_SMR_DATE019",
 PARTITION "P020"
   TABLESPACE "TS_HP_SMR_DATE020",
 PARTITION "P021"
   TABLESPACE "TS_HP_SMR_DATE021",
 PARTITION "P022"
   TABLESPACE "TS_HP_SMR_DATE022",
 PARTITION "P023"
   TABLESPACE "TS_HP_SMR_DATE023",
 PARTITION "P024"
   TABLESPACE "TS_HP_SMR_DATE024",
 PARTITION "P025"
   TABLESPACE "TS_HP_SMR_DATE025",
 PARTITION "P026"
   TABLESPACE "TS_HP_SMR_DATE026",
 PARTITION "P027"
   TABLESPACE "TS_HP_SMR_DATE027",
 PARTITION "P028"
   TABLESPACE "TS_HP_SMR_DATE028",
 PARTITION "P029"
   TABLESPACE "TS_HP_SMR_DATE029",
 PARTITION "P030"
   TABLESPACE "TS_HP_SMR_DATE030",
 PARTITION "P031"
   TABLESPACE "TS_HP_SMR_DATE031",
 PARTITION "P032"
   TABLESPACE "TS_HP_SMR_DATE032")
  PARALLEL ;


insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P001) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P002) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P003) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P004) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P005) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P006) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P007) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P008) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P009) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P010) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P011) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P012) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P013) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P014) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P015) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P016) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P017) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P018) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P019) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P020) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P021) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P022) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P023) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P024) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P025) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P026) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P027) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P028) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P029) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P030) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P031) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_MIGRATE,4) append */ into HP_SUMMARY_DATE_MIGRATE (select /*+ parallel(hp_summary_date,4) */
HPP_MSISDN,HPP_IMSI,HPP_IMEI,HPP_DAYS from hp_summary_date partition(P032) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;









rename hp_summary_date to hp_summary_date_before_mig;
rename HP_SUMMARY_DATE_MIGRATE to hp_summary_date;

alter index IX_HP_SUM_DATE_PH_IME_IMS rename to IX_HP_SUM_DATE_PH_IME_IMS_OLD;
alter index IX_HP_SUM_DATE_PH_IME_IMS_MIG rename to IX_HP_SUM_DATE_PH_IME_IMS;
