CREATE TABLESPACE TS_HP_SMR_DATE_BK001 DATAFILE '/home/cellc/temp/tshpsmr01.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK002 DATAFILE '/home/cellc/temp/tshpsmr02.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK003 DATAFILE '/home/cellc/temp/tshpsmr03.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK004 DATAFILE '/home/cellc/temp/tshpsmr04.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK005 DATAFILE '/home/cellc/temp/tshpsmr05.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK006 DATAFILE '/home/cellc/temp/tshpsmr06.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK007 DATAFILE '/home/cellc/temp/tshpsmr07.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK008 DATAFILE '/home/cellc/temp/tshpsmr08.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK009 DATAFILE '/home/cellc/temp/tshpsmr09.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK010 DATAFILE '/home/cellc/temp/tshpsmr10.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK011 DATAFILE '/home/cellc/temp/tshpsmr11.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK012 DATAFILE '/home/cellc/temp/tshpsmr12.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK013 DATAFILE '/home/cellc/temp/tshpsmr13.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK014 DATAFILE '/home/cellc/temp/tshpsmr14.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK015 DATAFILE '/home/cellc/temp/tshpsmr15.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK016 DATAFILE '/home/cellc/temp/tshpsmr16.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK017 DATAFILE '/home/cellc/temp/tshpsmr17.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK018 DATAFILE '/home/cellc/temp/tshpsmr18.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK019 DATAFILE '/home/cellc/temp/tshpsmr19.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK020 DATAFILE '/home/cellc/temp/tshpsmr20.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK021 DATAFILE '/home/cellc/temp/tshpsmr21.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK022 DATAFILE '/home/cellc/temp/tshpsmr22.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK023 DATAFILE '/home/cellc/temp/tshpsmr23.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK024 DATAFILE '/home/cellc/temp/tshpsmr24.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK025 DATAFILE '/home/cellc/temp/tshpsmr25.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK026 DATAFILE '/home/cellc/temp/tshpsmr26.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK027 DATAFILE '/home/cellc/temp/tshpsmr27.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK028 DATAFILE '/home/cellc/temp/tshpsmr28.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK029 DATAFILE '/home/cellc/temp/tshpsmr29.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK030 DATAFILE '/home/cellc/temp/tshpsmr30.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK031 DATAFILE '/home/cellc/temp/tshpsmr31.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_HP_SMR_DATE_BK032 DATAFILE '/home/cellc/temp/tshpsmr32.dbf' SIZE 5M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLE HP_SUMMARY_DATE_BK
(
 	HPP_MSISDN		   VARCHAR2(25) NOT NULL,
	HPP_IMSI		   VARCHAR2(20) NOT NULL,
	HPP_IMEI		   VARCHAR2(20) NOT NULL,
	HPP_DAYS		   NUMBER(10)   NOT NULL
) 
PARTITION BY HASH(HPP_MSISDN,HPP_IMEI,HPP_IMSI)
(
	PARTITION P001 TABLESPACE TS_HP_SMR_DATE_BK001, 
	PARTITION P002 TABLESPACE TS_HP_SMR_DATE_BK002,
	PARTITION P003 TABLESPACE TS_HP_SMR_DATE_BK003,
	PARTITION P004 TABLESPACE TS_HP_SMR_DATE_BK004,
	PARTITION P005 TABLESPACE TS_HP_SMR_DATE_BK005,
	PARTITION P006 TABLESPACE TS_HP_SMR_DATE_BK006,
	PARTITION P007 TABLESPACE TS_HP_SMR_DATE_BK007,
	PARTITION P008 TABLESPACE TS_HP_SMR_DATE_BK008,
	PARTITION P009 TABLESPACE TS_HP_SMR_DATE_BK009, 
	PARTITION P010 TABLESPACE TS_HP_SMR_DATE_BK010,
	PARTITION P011 TABLESPACE TS_HP_SMR_DATE_BK011,
	PARTITION P012 TABLESPACE TS_HP_SMR_DATE_BK012,
	PARTITION P013 TABLESPACE TS_HP_SMR_DATE_BK013,
	PARTITION P014 TABLESPACE TS_HP_SMR_DATE_BK014,
	PARTITION P015 TABLESPACE TS_HP_SMR_DATE_BK015,
	PARTITION P016 TABLESPACE TS_HP_SMR_DATE_BK016,
	PARTITION P017 TABLESPACE TS_HP_SMR_DATE_BK017, 
	PARTITION P018 TABLESPACE TS_HP_SMR_DATE_BK018,
	PARTITION P019 TABLESPACE TS_HP_SMR_DATE_BK019,
	PARTITION P020 TABLESPACE TS_HP_SMR_DATE_BK020,
	PARTITION P021 TABLESPACE TS_HP_SMR_DATE_BK021,
	PARTITION P022 TABLESPACE TS_HP_SMR_DATE_BK022,
	PARTITION P023 TABLESPACE TS_HP_SMR_DATE_BK023,
	PARTITION P024 TABLESPACE TS_HP_SMR_DATE_BK024,
	PARTITION P025 TABLESPACE TS_HP_SMR_DATE_BK025, 
	PARTITION P026 TABLESPACE TS_HP_SMR_DATE_BK026,
	PARTITION P027 TABLESPACE TS_HP_SMR_DATE_BK027,
	PARTITION P028 TABLESPACE TS_HP_SMR_DATE_BK028,
	PARTITION P029 TABLESPACE TS_HP_SMR_DATE_BK029,
	PARTITION P030 TABLESPACE TS_HP_SMR_DATE_BK030,
	PARTITION P031 TABLESPACE TS_HP_SMR_DATE_BK031,
	PARTITION P032 TABLESPACE TS_HP_SMR_DATE_BK032
) ;

				

  CREATE INDEX IX_HP_SUM_DATE_PH_IME_IMS_BK ON HP_SUMMARY_DATE_BK ("HPP_MSISDN", "HPP_IMEI", "HPP_IMSI")
  PCTFREE 10 INITRANS 2 MAXTRANS 255  NOLOGGING
  STORAGE(
  BUFFER_POOL DEFAULT) LOCAL
 (PARTITION "P001"
   TABLESPACE "TS_HP_SMR_DATE_BK001",
 PARTITION "P002"
   TABLESPACE "TS_HP_SMR_DATE_BK002",
 PARTITION "P003"
   TABLESPACE "TS_HP_SMR_DATE_BK003",
 PARTITION "P004"
   TABLESPACE "TS_HP_SMR_DATE_BK004",
 PARTITION "P005"
   TABLESPACE "TS_HP_SMR_DATE_BK005",
 PARTITION "P006"
   TABLESPACE "TS_HP_SMR_DATE_BK006",
 PARTITION "P007"
   TABLESPACE "TS_HP_SMR_DATE_BK007",
 PARTITION "P008"
   TABLESPACE "TS_HP_SMR_DATE_BK008",
 PARTITION "P009"
   TABLESPACE "TS_HP_SMR_DATE_BK009",
 PARTITION "P010"
   TABLESPACE "TS_HP_SMR_DATE_BK010",
 PARTITION "P011"
   TABLESPACE "TS_HP_SMR_DATE_BK011",
 PARTITION "P012"
   TABLESPACE "TS_HP_SMR_DATE_BK012",
 PARTITION "P013"
   TABLESPACE "TS_HP_SMR_DATE_BK013",
 PARTITION "P014"
   TABLESPACE "TS_HP_SMR_DATE_BK014",
 PARTITION "P015"
   TABLESPACE "TS_HP_SMR_DATE_BK015",
 PARTITION "P016"
   TABLESPACE "TS_HP_SMR_DATE_BK016",
 PARTITION "P017"
   TABLESPACE "TS_HP_SMR_DATE_BK017",
 PARTITION "P018"
   TABLESPACE "TS_HP_SMR_DATE_BK018",
 PARTITION "P019"
   TABLESPACE "TS_HP_SMR_DATE_BK019",
 PARTITION "P020"
   TABLESPACE "TS_HP_SMR_DATE_BK020",
 PARTITION "P021"
   TABLESPACE "TS_HP_SMR_DATE_BK021",
 PARTITION "P022"
   TABLESPACE "TS_HP_SMR_DATE_BK022",
 PARTITION "P023"
   TABLESPACE "TS_HP_SMR_DATE_BK023",
 PARTITION "P024"
   TABLESPACE "TS_HP_SMR_DATE_BK024",
 PARTITION "P025"
   TABLESPACE "TS_HP_SMR_DATE_BK025",
 PARTITION "P026"
   TABLESPACE "TS_HP_SMR_DATE_BK026",
 PARTITION "P027"
   TABLESPACE "TS_HP_SMR_DATE_BK027",
 PARTITION "P028"
   TABLESPACE "TS_HP_SMR_DATE_BK028",
 PARTITION "P029"
   TABLESPACE "TS_HP_SMR_DATE_BK029",
 PARTITION "P030"
   TABLESPACE "TS_HP_SMR_DATE_BK030",
 PARTITION "P031"
   TABLESPACE "TS_HP_SMR_DATE_BK031",
 PARTITION "P032"
   TABLESPACE "TS_HP_SMR_DATE_BK032")
  PARALLEL ;



CREATE TABLE HP_SUMMARY_DATE_BK_MIG
(
 	HPP_MSISDN		   VARCHAR2(25) NOT NULL,
	HPP_IMSI		   VARCHAR2(20) NOT NULL,
	HPP_IMEI		   VARCHAR2(20) NOT NULL,
	HPP_DAYS		   NUMBER(10)   NOT NULL
) 
PARTITION BY HASH(HPP_MSISDN,HPP_IMEI,HPP_IMSI)
(
	PARTITION P001 TABLESPACE TS_HP_SMR_DATE_BK001, 
	PARTITION P002 TABLESPACE TS_HP_SMR_DATE_BK002,
	PARTITION P003 TABLESPACE TS_HP_SMR_DATE_BK003,
	PARTITION P004 TABLESPACE TS_HP_SMR_DATE_BK004,
	PARTITION P005 TABLESPACE TS_HP_SMR_DATE_BK005,
	PARTITION P006 TABLESPACE TS_HP_SMR_DATE_BK006,
	PARTITION P007 TABLESPACE TS_HP_SMR_DATE_BK007,
	PARTITION P008 TABLESPACE TS_HP_SMR_DATE_BK008,
	PARTITION P009 TABLESPACE TS_HP_SMR_DATE_BK009, 
	PARTITION P010 TABLESPACE TS_HP_SMR_DATE_BK010,
	PARTITION P011 TABLESPACE TS_HP_SMR_DATE_BK011,
	PARTITION P012 TABLESPACE TS_HP_SMR_DATE_BK012,
	PARTITION P013 TABLESPACE TS_HP_SMR_DATE_BK013,
	PARTITION P014 TABLESPACE TS_HP_SMR_DATE_BK014,
	PARTITION P015 TABLESPACE TS_HP_SMR_DATE_BK015,
	PARTITION P016 TABLESPACE TS_HP_SMR_DATE_BK016,
	PARTITION P017 TABLESPACE TS_HP_SMR_DATE_BK017, 
	PARTITION P018 TABLESPACE TS_HP_SMR_DATE_BK018,
	PARTITION P019 TABLESPACE TS_HP_SMR_DATE_BK019,
	PARTITION P020 TABLESPACE TS_HP_SMR_DATE_BK020,
	PARTITION P021 TABLESPACE TS_HP_SMR_DATE_BK021,
	PARTITION P022 TABLESPACE TS_HP_SMR_DATE_BK022,
	PARTITION P023 TABLESPACE TS_HP_SMR_DATE_BK023,
	PARTITION P024 TABLESPACE TS_HP_SMR_DATE_BK024,
	PARTITION P025 TABLESPACE TS_HP_SMR_DATE_BK025, 
	PARTITION P026 TABLESPACE TS_HP_SMR_DATE_BK026,
	PARTITION P027 TABLESPACE TS_HP_SMR_DATE_BK027,
	PARTITION P028 TABLESPACE TS_HP_SMR_DATE_BK028,
	PARTITION P029 TABLESPACE TS_HP_SMR_DATE_BK029,
	PARTITION P030 TABLESPACE TS_HP_SMR_DATE_BK030,
	PARTITION P031 TABLESPACE TS_HP_SMR_DATE_BK031,
	PARTITION P032 TABLESPACE TS_HP_SMR_DATE_BK032
) ;


  CREATE INDEX IX_HP_SUM_DATE_PH_IME_IMS_BKM ON HP_SUMMARY_DATE_BK_MIG ("HPP_MSISDN", "HPP_IMEI", "HPP_IMSI")
  PCTFREE 10 INITRANS 2 MAXTRANS 255  NOLOGGING
  STORAGE(
  BUFFER_POOL DEFAULT) LOCAL
 (PARTITION "P001"
   TABLESPACE "TS_HP_SMR_DATE_BK001",
 PARTITION "P002"
   TABLESPACE "TS_HP_SMR_DATE_BK002",
 PARTITION "P003"
   TABLESPACE "TS_HP_SMR_DATE_BK003",
 PARTITION "P004"
   TABLESPACE "TS_HP_SMR_DATE_BK004",
 PARTITION "P005"
   TABLESPACE "TS_HP_SMR_DATE_BK005",
 PARTITION "P006"
   TABLESPACE "TS_HP_SMR_DATE_BK006",
 PARTITION "P007"
   TABLESPACE "TS_HP_SMR_DATE_BK007",
 PARTITION "P008"
   TABLESPACE "TS_HP_SMR_DATE_BK008",
 PARTITION "P009"
   TABLESPACE "TS_HP_SMR_DATE_BK009",
 PARTITION "P010"
   TABLESPACE "TS_HP_SMR_DATE_BK010",
 PARTITION "P011"
   TABLESPACE "TS_HP_SMR_DATE_BK011",
 PARTITION "P012"
   TABLESPACE "TS_HP_SMR_DATE_BK012",
 PARTITION "P013"
   TABLESPACE "TS_HP_SMR_DATE_BK013",
 PARTITION "P014"
   TABLESPACE "TS_HP_SMR_DATE_BK014",
 PARTITION "P015"
   TABLESPACE "TS_HP_SMR_DATE_BK015",
 PARTITION "P016"
   TABLESPACE "TS_HP_SMR_DATE_BK016",
 PARTITION "P017"
   TABLESPACE "TS_HP_SMR_DATE_BK017",
 PARTITION "P018"
   TABLESPACE "TS_HP_SMR_DATE_BK018",
 PARTITION "P019"
   TABLESPACE "TS_HP_SMR_DATE_BK019",
 PARTITION "P020"
   TABLESPACE "TS_HP_SMR_DATE_BK020",
 PARTITION "P021"
   TABLESPACE "TS_HP_SMR_DATE_BK021",
 PARTITION "P022"
   TABLESPACE "TS_HP_SMR_DATE_BK022",
 PARTITION "P023"
   TABLESPACE "TS_HP_SMR_DATE_BK023",
 PARTITION "P024"
   TABLESPACE "TS_HP_SMR_DATE_BK024",
 PARTITION "P025"
   TABLESPACE "TS_HP_SMR_DATE_BK025",
 PARTITION "P026"
   TABLESPACE "TS_HP_SMR_DATE_BK026",
 PARTITION "P027"
   TABLESPACE "TS_HP_SMR_DATE_BK027",
 PARTITION "P028"
   TABLESPACE "TS_HP_SMR_DATE_BK028",
 PARTITION "P029"
   TABLESPACE "TS_HP_SMR_DATE_BK029",
 PARTITION "P030"
   TABLESPACE "TS_HP_SMR_DATE_BK030",
 PARTITION "P031"
   TABLESPACE "TS_HP_SMR_DATE_BK031",
 PARTITION "P032"
   TABLESPACE "TS_HP_SMR_DATE_BK032")
  PARALLEL ;



insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P001) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P002) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P003) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P004) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P005) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P006) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P007) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P008) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P009) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P010) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P011) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P012) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P013) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P014) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P015) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P016) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P017) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P018) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P019) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P020) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P021) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P022) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P023) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P024) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P025) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P026) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P027) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P028) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P029) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P030) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P031) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;

insert /*+ parallel(HP_SUMMARY_DATE_BK_MIG,4) append */ into HP_SUMMARY_DATE_BK_MIG (select /*+ parallel(HP_SUMMARY_DATE_BK,4) */ HPP_MSISDN, HPP_IMSI, HPP_IMEI, HPP_DAYS from HP_SUMMARY_DATE_BK partition(P032) where HPP_DAYS > 2456912) order by HPP_IMEI,HPP_MSISDN,HPP_IMSI;


rename HP_SUMMARY_DATE_BK to HP_SUMMARY_DATE_BK_B4MIG;
rename HP_SUMMARY_DATE_BK to HP_SUMMARY_DATE_BK;

alter index IX_HP_SUM_DATE_PH_IME_IMS_BK rename to IX_HP_SUM_DATE_PH_IME_IMS_OLD;
alter index IX_HP_SUM_DATE_PH_IME_IMS_BKM rename to IX_HP_SUM_DATE_PH_IME_IMS_BK;
