sqlplus $DB_USER/$DB_PASSWORD << EOF
whenever sqlerror exit 5;
whenever oserror exit 5;

DELETE FROM BDWRDW_FIELD_CONFIGURATION  WHERE RECORD_NAME = 'CALL_DETAIL_RECORD' ;
DELETE FROM BDWRDW_RECORD_CONFIGURATION  WHERE BLOCK_NAME = 'MTX_RECORD_BLOCK' ;

INSERT INTO BDWRDW_RECORD_CONFIGURATION VALUES ('MTX_RECORD_BLOCK','CALL_DETAIL_RECORD','F7',290,'N') ;
INSERT INTO BDWRDW_FIELD_CONFIGURATION VALUES ('CALL_DETAIL_RECORD','CALLER_NUMBER',28,800) ;

commit ;

EOF

if test $? -eq 5
then
	exit 1
fi

exit 0

