sqlplus $DB_USER/$DB_PASSWORD << EOF
whenever sqlerror exit 5;
whenever oserror exit 5;

DELETE FROM RFF_FIELD_POSITION_MAP WHERE DATASOURCE_NAME LIKE '%MTX12LNP_TEST%' ;
DELETE FROM PARSER WHERE PARSER_NAME LIKE '%MTX12LNP_PARSER%' ;

DELETE FROM BDWRDW_FIELD_CONFIGURATION  WHERE RECORD_NAME = 'CALL_DETAIL_RECORD' ;
DELETE FROM BDWRDW_BLOCK_CONFIGURATION WHERE PARSER_NAME = 'MTX12LNP_PARSER' ;
DELETE FROM BDWRDW_RECORD_CONFIGURATION  WHERE BLOCK_NAME = 'MTX_RECORD_BLOCK' ;
DELETE FROM BDWRDW_PARSER_CONFIGURATION  WHERE PARSER_NAME = 'MTX12LNP_PARSER' ;




INSERT INTO PARSER VALUES ('MTX12LNP_TEST',3,'MTX12LNP_PARSER');
INSERT INTO BDWRDW_PARSER_CONFIGURATION VALUES ('MTX12LNP_PARSER','BLOCK_CODE_FIELD_SIZE',2) ;
INSERT INTO BDWRDW_BLOCK_CONFIGURATION VALUES ('MTX12LNP_PARSER','MTX_RECORD_BLOCK','C1C1',2048,10,0,2) ;
INSERT INTO BDWRDW_RECORD_CONFIGURATION VALUES ('MTX_RECORD_BLOCK','CALL_DETAIL_RECORD','F7',3090,'N') ;
INSERT INTO BDWRDW_FIELD_CONFIGURATION VALUES ('CALL_DETAIL_RECORD','CALLER_NUMBER',28,24) ;
INSERT INTO BDWRDW_FIELD_CONFIGURATION VALUES ('CALL_DETAIL_RECORD','ORIGINATION_TIME',312,9) ;
INSERT INTO RFF_FIELD_POSITION_MAP VALUES ('MTX12LNP_TEST', 'CALLER_NUMBER', 3, '') ;

commit ;

EOF

if test $? -eq 5
then
	exit 1
fi

exit 0

