sqlplus $DB_USER/$DB_PASSWORD<<EOF
whenever sqlerror exit 5;
whenever oserror exit 5;
delete from datasource_info where datasource_name like '%ALLTEL.ROAMEX' ;
delete from parser where parser_name like 'ALLTEL%' ;
insert into datasource_info values('ALLTEL.ROAMEX',2) ;
insert into parser values('ALLTEL.ROAMEX',1,'ALLTEL.ROAMEX') ;

DELETE FROM ASN1_CALLMODULE_PATH WHERE PARSER_NAME = 'ALLTEL.ROAMEX' AND CALL_MODULE = 'AMPS_MTN' ;
DELETE FROM ASN1_CALLMODULE_PATH WHERE PARSER_NAME = 'ALLTEL.ROAMEX' AND CALL_MODULE = 'AMPS_MLN' ;
DELETE FROM ASN1_FIELD_PATH WHERE CALL_MODULE = 'AMPS_MTN' ;
DELETE FROM ASN1_FIELD_PATH WHERE CALL_MODULE = 'AMPS_MLN' ;
INSERT INTO ASN1_CALLMODULE_PATH VALUES ('ALLTEL.ROAMEX','AMPS_MTN','1-4-5') ;
INSERT INTO ASN1_CALLMODULE_PATH VALUES ('ALLTEL.ROAMEX','AMPS_MLN','1-6-A') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTN','ASN_IMEI','1','T') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MLN','ASN_IMEI','1','T') ;

commit ;

EOF

if [ $? -ne 0 ]
then
    exit 1
fi

