sqlplus $DB_USER/$DB_PASSWORD<<EOF
whenever sqlerror exit 5;
whenever oserror exit 5;

DELETE FROM ASN1_PARSER_CONFIGURATION WHERE PARSER_NAME='ALLTEL.ROAMEX' ;
INSERT INTO ASN1_PARSER_CONFIGURATION VALUES ('ALLTEL.ROAMEX','RECORD_HEADER_LENGTH','4') ;

DELETE FROM ASN1_CALLMODULE_PATH WHERE PARSER_NAME='ALLTEL.ROAMEX' ;
INSERT INTO ASN1_CALLMODULE_PATH VALUES ('ALLTEL.ROAMEX','AMPS_MOC','1-1') ;
INSERT INTO ASN1_CALLMODULE_PATH VALUES ('ALLTEL.ROAMEX','AMPS_MTC','1-2') ;
INSERT INTO ASN1_CALLMODULE_PATH VALUES ('ALLTEL.ROAMEX','GSM_MOC','2-1') ;
INSERT INTO ASN1_CALLMODULE_PATH VALUES ('ALLTEL.ROAMEX','GSM_MTC','2-2') ;

DELETE FROM ASN1_FIELD_PATH ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_IMEI','1','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_IMSI','2','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_DATE_FOR_START_OF_CALL','10','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_TIME_FOR_START_OF_CALL','11','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_CALL_DURATION','15','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_OTHER_PARTY_NUMBER','17','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_MSISDN' ,'0','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_CALL_STATUS' ,'27','TV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_TOLL_INDICATOR','28-9','TV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_SERVING_SWITCH_ID','5','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_SERVING_SWITCH_NUMBER','8','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_HOME_ROAM_INDICATOR','28','TV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_FEATURE_FLAGS_CALL_WAITING','34-5','T') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_FEATURE_FLAGS_CONFERENCE_CALL','34-9','T') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_FEATURE_FLAGS_HOTLINE','34-20','T') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_FEATURE_FLAGS_EMERGENCY_CALL','34-22','T') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_FEATURE_FLAGS_CALL_ON_HOLD','34-23','T') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MOC','ASN_FEATURE_FLAGS_VOICEMAIL','34-29','T') ;

INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_IMEI','1','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_IMSI','2','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_DATE_FOR_START_OF_CALL','10','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_TIME_FOR_START_OF_CALL','11','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_CALL_DURATION','15','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_OTHER_PARTY_NUMBER','3','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_MSISDN' ,'0','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_CALL_STATUS' ,'27','TV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_TOLL_INDICATOR','28-9','TV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_SERVING_SWITCH_ID','5','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_SERVING_SWITCH_NUMBER','8','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_HOME_ROAM_INDICATOR','28','TV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_FEATURE_FLAGS_CALL_WAITING','34-5','T') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_FEATURE_FLAGS_CONFERENCE_CALL','34-9','T') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_FEATURE_FLAGS_HOTLINE','34-20','T') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_FEATURE_FLAGS_EMERGENCY_CALL','34-22','T') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_FEATURE_FLAGS_CALL_ON_HOLD','34-23','T') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('AMPS_MTC','ASN_FEATURE_FLAGS_VOICEMAIL','34-29','T') ;

INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MOC','ASN_IMEI','1','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MOC','ASN_IMSI','2','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MOC','ASN_DATE_FOR_START_OF_CALL','11','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MOC','ASN_TIME_FOR_START_OF_CALL','12','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MOC','ASN_CALL_DURATION','16','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MOC','ASN_OTHER_PARTY_NUMBER','18','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MOC','ASN_MSISDN' ,'0','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MOC','ASN_CALL_STATUS' ,'28','TV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MOC','ASN_TOLL_INDICATOR','29-9','TV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MOC','ASN_SERVING_SWITCH_ID','6','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MOC','ASN_SERVING_SWITCH_NUMBER','9','TLV') ;


INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MTC','ASN_IMEI','1','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MTC','ASN_IMSI','2','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MTC','ASN_DATE_FOR_START_OF_CALL','11','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MTC','ASN_TIME_FOR_START_OF_CALL','12','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MTC','ASN_CALL_DURATION','16','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MTC','ASN_OTHER_PARTY_NUMBER','3','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MTC','ASN_MSISDN' ,'0','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MTC','ASN_CALL_STATUS' ,'28','TV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MTC','ASN_TOLL_INDICATOR','29-9','TV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MTC','ASN_SERVING_SWITCH_ID','6','TLV') ;
INSERT INTO ASN1_FIELD_PATH VALUES ('GSM_MTC','ASN_SERVING_SWITCH_NUMBER','9','TLV') ;
COMMIT ;
EOF

if [ $? -ne 0 ]
then
    exit 1
fi

