#!/bin/bash

sqlplus -s $DB_USER/$DB_PASSWORD << EOF
	Delete from RATE_PLANS ;
	Delete from TIME_ZONE_RATE_TYPES ;
	Delete from NETWORKS_RATER_SPECIAL_NUMBERS ;
	Delete from RATER_SPECIAL_NUMBERS ;
	Delete from RATE_TYPES ;
	Delete from RATE_PER_CALLS ;
	Delete from FREE_NUMBERS_NETWORKS ;
	Delete from FREE_NUMBERS ;
	Delete from DEFAULT_RATES ;
	Delete from RATER_COUNTRY_CODES ;
	Delete from ORG_DEST_LINKS ;
	Delete from ZONE_CODES ;
	Delete from SDR_RATES ;
	
	-- INSERTING into RATER_COUNTRY_CODES
	Insert into RATER_COUNTRY_CODES ("ID","COUNTRY_CODE","DESCRIPTION") values ('1','+91','India');
	Insert into RATER_COUNTRY_CODES ("ID","COUNTRY_CODE","DESCRIPTION") values ('2','+92','SriLanka');
	Insert into RATER_COUNTRY_CODES ("ID","COUNTRY_CODE","DESCRIPTION") values ('3','+1','USA');

	-- INSERTING into DEFAULT_RATES
	Insert into DEFAULT_RATES ("ID","RATE_TYPE","CALL_TYPE","PULSE","RATE") values ('1024','GS','V','60','200');
	Insert into DEFAULT_RATES ("ID","RATE_TYPE","CALL_TYPE","PULSE","RATE") values ('1025','GS','S','0','100');
	Insert into DEFAULT_RATES ("ID","RATE_TYPE","CALL_TYPE","PULSE","RATE") values ('1026','GS','M','1000','250');
	Insert into DEFAULT_RATES ("ID","RATE_TYPE","CALL_TYPE","PULSE","RATE") values ('1027','GS','G','1000','300');

	-- INSERTING into FREE_NUMBERS
	Insert into FREE_NUMBERS ("ID","DESCRIPTION","FREE_NUMBER") values ('1','Toll Free Numbers.','+919880534514');

	
	-- INSERTING into FREE_NUMBERS_NETWORKS
	Insert into FREE_NUMBERS_NETWORKS ("FREE_NUMBER_ID","NETWORK_ID") values ('1','1');
	Insert into FREE_NUMBERS_NETWORKS ("FREE_NUMBER_ID","NETWORK_ID") values ('1','2');
	Insert into FREE_NUMBERS_NETWORKS ("FREE_NUMBER_ID","NETWORK_ID") values ('1','3');
	Insert into FREE_NUMBERS_NETWORKS ("FREE_NUMBER_ID","NETWORK_ID") values ('1','4');
	
	-- INSERTING into ZONE_CODES
	Insert into ZONE_CODES ("ID","ZONE_CODE","DESCRIPTION") values ('1026','ZoneNational','National Zone');
	Insert into ZONE_CODES ("ID","ZONE_CODE","DESCRIPTION") values ('1027','ZoneInternational','Intenational Zone ');
	Insert into ZONE_CODES ("ID","ZONE_CODE","DESCRIPTION") values ('1025','Default Zone Code','Default Zone Code');

	-- INSERTING into ORG_DEST_LINKS
	Insert into ORG_DEST_LINKS ("ID","ORG_GEO_CODE","DEST_GEO_CODE","ZONE_CODE","NATIONAL_FLAG","LETTER_CODE") values ('1027','+91','+1','ZoneInternational','N','1');
	Insert into ORG_DEST_LINKS ("ID","ORG_GEO_CODE","DEST_GEO_CODE","ZONE_CODE","NATIONAL_FLAG","LETTER_CODE") values ('1025','+91','+91','ZoneNational','Y','1');
	Insert into ORG_DEST_LINKS ("ID","ORG_GEO_CODE","DEST_GEO_CODE","ZONE_CODE","NATIONAL_FLAG","LETTER_CODE") values ('1026','+91','+92','ZoneInternational','N','1');

	-- INSERTING into RATE_TYPES
	Insert into RATE_TYPES ("ID","RATE_TYPE","DESCRIPTION") values ('1','RT_1','Rate Type 1');
	Insert into RATE_TYPES ("ID","RATE_TYPE","DESCRIPTION") values ('2','RT_2','Test rate Type 2');

	-- INSERTING into RATER_SPECIAL_NUMBERS
	Insert into RATER_SPECIAL_NUMBERS ("ID","DESCRIPTION","SPECIAL_NUMBER","SERVICE_CATEGORY","MIN_CHARGEABLE_UNIT","MIN_CHARGE","PULSE","RATE","PSTN_MIN_CHARGEABLE_UNIT","PSTN_MIN_CHARGE","PSTN_PULSE","PSTN_RATE","EXTRA_CHARGE","CALL_TYPE","PMN",MATCH_TYPE) values ('1024','Test rate Special','+919880534516','GS','60','2','60','1','0','0','0','0','10','V','','PM');

	-- INSERTING into NETWORKS_RATER_SPECIAL_NUMBERS
	Insert into NETWORKS_RATER_SPECIAL_NUMBERS ("RATER_SPECIAL_NUMBER_ID","NETWORK_ID") values ('1024','1024');
	Insert into NETWORKS_RATER_SPECIAL_NUMBERS ("RATER_SPECIAL_NUMBER_ID","NETWORK_ID") values ('1024','1025');
	Insert into NETWORKS_RATER_SPECIAL_NUMBERS ("RATER_SPECIAL_NUMBER_ID","NETWORK_ID") values ('1024','1026');
	Insert into NETWORKS_RATER_SPECIAL_NUMBERS ("RATER_SPECIAL_NUMBER_ID","NETWORK_ID") values ('1024','1027');

	-- INSERTING into TIME_ZONE_RATE_TYPES
	Insert into TIME_ZONE_RATE_TYPES ("ID","DAY_TYPE","START_TIME","END_TIME","SERVICE_CATEGORY","NATIONAL_FLAG","RATE_TYPE") values ('1024','AD',to_date('14/10/08 00:00:00','DD/MM/YY HH24:MI:SS'),to_date('14/10/08 23:59:59','DD/MM/YY HH24:MI:SS'),'GS','Y','RT_1');
	Insert into TIME_ZONE_RATE_TYPES ("ID","DAY_TYPE","START_TIME","END_TIME","SERVICE_CATEGORY","NATIONAL_FLAG","RATE_TYPE") values ('1025','AD',to_date('14/10/08 00:00:00','DD/MM/YY HH24:MI:SS'),to_date('14/10/08 23:59:59','DD/MM/YY HH24:MI:SS'),'GS','N','RT_2');

	-- INSERTING into RATE_PLANS
	Insert into RATE_PLANS ("ID","RATE_PLAN","ROAMER_FLAG","RATE_PLAN_ID","ORG_NUMBER_TYPE","DEST_NUMBER_TYPE","ZONE_CODE","RATE_TYPE","CALL_TYPE","SERVICE_BAND","MIN_CHARGEABLE_UNIT","MIN_CHARGE","PULSE","RATE","PSTN_MIN_CHARGEABLE_UNIT","PSTN_MIN_CHARGE","PSTN_PULSE","PSTN_RATE","FF_MIN_CHARGEABLE_UNIT","FF_MIN_CHARGE","FF_PULSE","FF_RATE","FF_PSTN_MIN_CHARGEABLE_UNIT","FF_PSTN_MIN_CHARGE","FF_PSTN_PULSE","FF_PSTN_RATE","EXTRA_CHARGE","CALL_CATEGORY","PMN") values ('1024','Rate_1','N','Rate_1','GS','GSM','ZoneNational','RT_1','V','C,O,F,I','60','1','60','1','0','0','0','0','0','0','0','0','0','0','0','0','0','2','HPMN');
	Insert into RATE_PLANS ("ID","RATE_PLAN","ROAMER_FLAG","RATE_PLAN_ID","ORG_NUMBER_TYPE","DEST_NUMBER_TYPE","ZONE_CODE","RATE_TYPE","CALL_TYPE","SERVICE_BAND","MIN_CHARGEABLE_UNIT","MIN_CHARGE","PULSE","RATE","PSTN_MIN_CHARGEABLE_UNIT","PSTN_MIN_CHARGE","PSTN_PULSE","PSTN_RATE","FF_MIN_CHARGEABLE_UNIT","FF_MIN_CHARGE","FF_PULSE","FF_RATE","FF_PSTN_MIN_CHARGEABLE_UNIT","FF_PSTN_MIN_CHARGE","FF_PSTN_PULSE","FF_PSTN_RATE","EXTRA_CHARGE","CALL_CATEGORY","PMN") values ('1025','Rate_1','N','Rate_1','GS','GSM','ZoneNational','RT_1','S','C,O,F,I','0','0','0','0.5','0','0','0','0','0','0','0','0','0','0','0','0','0','2','HPMN');
	Insert into RATE_PLANS ("ID","RATE_PLAN","ROAMER_FLAG","RATE_PLAN_ID","ORG_NUMBER_TYPE","DEST_NUMBER_TYPE","ZONE_CODE","RATE_TYPE","CALL_TYPE","SERVICE_BAND","MIN_CHARGEABLE_UNIT","MIN_CHARGE","PULSE","RATE","PSTN_MIN_CHARGEABLE_UNIT","PSTN_MIN_CHARGE","PSTN_PULSE","PSTN_RATE","FF_MIN_CHARGEABLE_UNIT","FF_MIN_CHARGE","FF_PULSE","FF_RATE","FF_PSTN_MIN_CHARGEABLE_UNIT","FF_PSTN_MIN_CHARGE","FF_PSTN_PULSE","FF_PSTN_RATE","EXTRA_CHARGE","CALL_CATEGORY","PMN") values ('1029','Rate_1','N','Rate_1','GS','GSM','ZoneInternational','RT_2','V','C,O,F,I','60','10','60','10','0','0','0','0','0','0','0','0','0','0','0','0','0','3','HPMN');
	Insert into RATE_PLANS ("ID","RATE_PLAN","ROAMER_FLAG","RATE_PLAN_ID","ORG_NUMBER_TYPE","DEST_NUMBER_TYPE","ZONE_CODE","RATE_TYPE","CALL_TYPE","SERVICE_BAND","MIN_CHARGEABLE_UNIT","MIN_CHARGE","PULSE","RATE","PSTN_MIN_CHARGEABLE_UNIT","PSTN_MIN_CHARGE","PSTN_PULSE","PSTN_RATE","FF_MIN_CHARGEABLE_UNIT","FF_MIN_CHARGE","FF_PULSE","FF_RATE","FF_PSTN_MIN_CHARGEABLE_UNIT","FF_PSTN_MIN_CHARGE","FF_PSTN_PULSE","FF_PSTN_RATE","EXTRA_CHARGE","CALL_CATEGORY","PMN") values ('1027','Rate_1','N','Rate_1','GS','GSM','ZoneNational','RT_1','M','C,O,F,I','1000','5','1000','5','0','0','0','0','0','0','0','0','0','0','0','0','0','0','HPMN');
	Insert into RATE_PLANS ("ID","RATE_PLAN","ROAMER_FLAG","RATE_PLAN_ID","ORG_NUMBER_TYPE","DEST_NUMBER_TYPE","ZONE_CODE","RATE_TYPE","CALL_TYPE","SERVICE_BAND","MIN_CHARGEABLE_UNIT","MIN_CHARGE","PULSE","RATE","PSTN_MIN_CHARGEABLE_UNIT","PSTN_MIN_CHARGE","PSTN_PULSE","PSTN_RATE","FF_MIN_CHARGEABLE_UNIT","FF_MIN_CHARGE","FF_PULSE","FF_RATE","FF_PSTN_MIN_CHARGEABLE_UNIT","FF_PSTN_MIN_CHARGE","FF_PSTN_PULSE","FF_PSTN_RATE","EXTRA_CHARGE","CALL_CATEGORY","PMN") values ('1028','Rate_1','N','Rate_1','GS','GSM','ZoneNational','RT_1','G','C,O,F,I','1000','6','1000','6','0','0','0','0','0','0','0','0','0','0','0','0','0','0','HPMN');
	Insert into RATE_PLANS ("ID","RATE_PLAN","ROAMER_FLAG","RATE_PLAN_ID","ORG_NUMBER_TYPE","DEST_NUMBER_TYPE","ZONE_CODE","RATE_TYPE","CALL_TYPE","SERVICE_BAND","MIN_CHARGEABLE_UNIT","MIN_CHARGE","PULSE","RATE","PSTN_MIN_CHARGEABLE_UNIT","PSTN_MIN_CHARGE","PSTN_PULSE","PSTN_RATE","FF_MIN_CHARGEABLE_UNIT","FF_MIN_CHARGE","FF_PULSE","FF_RATE","FF_PSTN_MIN_CHARGEABLE_UNIT","FF_PSTN_MIN_CHARGE","FF_PSTN_PULSE","FF_PSTN_RATE","EXTRA_CHARGE","CALL_CATEGORY","PMN") values ('1030','Rate_1','N','Rate_1','GS','GSM','ZoneInternational','RT_2','S','C,O,F,I','0','5','0','5','0','0','0','0','0','0','0','0','0','0','0','0','0','3','HPMN');
	Insert into RATE_PLANS ("ID","RATE_PLAN","ROAMER_FLAG","RATE_PLAN_ID","ORG_NUMBER_TYPE","DEST_NUMBER_TYPE","ZONE_CODE","RATE_TYPE","CALL_TYPE","SERVICE_BAND","MIN_CHARGEABLE_UNIT","MIN_CHARGE","PULSE","RATE","PSTN_MIN_CHARGEABLE_UNIT","PSTN_MIN_CHARGE","PSTN_PULSE","PSTN_RATE","FF_MIN_CHARGEABLE_UNIT","FF_MIN_CHARGE","FF_PULSE","FF_RATE","FF_PSTN_MIN_CHARGEABLE_UNIT","FF_PSTN_MIN_CHARGE","FF_PSTN_PULSE","FF_PSTN_RATE","EXTRA_CHARGE","CALL_CATEGORY","PMN") values ('1031','Rate_1','N','Rate_1','GS','GSM','ZoneInternational','RT_2','M','C,O,F,I','1000','7.5','1000','7.5','0','0','0','0','0','0','0','0','0','0','0','0','0','0','HPMN');
	Insert into RATE_PLANS ("ID","RATE_PLAN","ROAMER_FLAG","RATE_PLAN_ID","ORG_NUMBER_TYPE","DEST_NUMBER_TYPE","ZONE_CODE","RATE_TYPE","CALL_TYPE","SERVICE_BAND","MIN_CHARGEABLE_UNIT","MIN_CHARGE","PULSE","RATE","PSTN_MIN_CHARGEABLE_UNIT","PSTN_MIN_CHARGE","PSTN_PULSE","PSTN_RATE","FF_MIN_CHARGEABLE_UNIT","FF_MIN_CHARGE","FF_PULSE","FF_RATE","FF_PSTN_MIN_CHARGEABLE_UNIT","FF_PSTN_MIN_CHARGE","FF_PSTN_PULSE","FF_PSTN_RATE","EXTRA_CHARGE","CALL_CATEGORY","PMN") values ('1032','Rate_1','N','Rate_1','GS','GSM','ZoneInternational','RT_2','G','C,O,F,I','1000','10','1000','10','0','0','0','0','0','0','0','0','0','0','0','0','0','0','HPMN');

	-- INSERTING into SDR_RATES
	Insert into SDR_RATES ("ID","START_DATE","END_DATE","SDR_VALUE") values (1,TO_DATE('12/10/2008', 'DD/MM/YYYY'),TO_DATE('14/10/2008', 'DD/MM/YYYY'),100);

	Update CONFIGURATIONS set "VALUE" = 'Rate_1' where CONFIG_KEY = 'ETISALAT_RATE_PLAN_ID' ;

	Update CONFIGURATIONS set "VALUE" = '10' where CONFIG_KEY = 'DEFAULT_SDR_RATE' ;
	Update CONFIGURATIONS set "VALUE" = '15' where CONFIG_KEY = 'PERCENTAGE_SDR_VALUE' ;
	Update CONFIGURATIONS set "VALUE" = '15' where CONFIG_KEY = 'MULTIPLICATION_SDR_FACTOR' ;
	Update CONFIGURATIONS set "VALUE" = '20' where CONFIG_KEY = 'FLAT_SDR_RATE' ;

	INSERT INTO RATE_PER_CALLS ("ID","SERVICE_NUMBER","DESCRIPTION","CALL_TYPE","SERVICE_CATEGORY","SERVICE_PROVIDER", "SERVICE_BAND","AIR_AMOUNT_PER_CALL","PSTN_AMOUNT_PER_CALL","EXTRA_CHARGE","PMN") VALUES (RATE_PER_CALLS_SEQ.NEXTVAL,'+356135','HELP - TEST SERVICES LINE','K','GS','N','O,F',499,'','','HPMN') ;
commit ;
EOF
