sed -i "s/(NATIONAL_FLAG IN ('Y','N'))/(NATIONAL_FLAG IN (''Y'',''N''))/g" modified_schema.xml
sed -i "s/(UPPER(NICKNAME_TYPE)='DAILYADDITION' OR UPPER(NICKNAME_TYPE)='REPLACEALL')/(UPPER(NICKNAME_TYPE)=''DAILYADDITION'' OR UPPER(NICKNAME_TYPE)=''REPLACEALL'')/g" modified_schema.xml
sed -i "s/(ROAMER_FLAG IN ('Y','N'))/(ROAMER_FLAG IN (''Y'',''N''))/g" modified_schema.xml
sed -i "s/(service_provider in ('Y','N'))/(service_provider in (''Y'',''N''))/g" modified_schema.xml
sed -i "s/(match_type in ('EM','PM'))/(match_type in (''EM'',''PM''))/g" modified_schema.xml

sed -i 's#<ObjectMapping ObjectName="ExpandableFieldMaps" DatabaseName="spark" TableName="EXPANDABLE_FIELD_MAPS" PrimaryKey="Ef1169Id" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Ef1169Name,Rv9195Id,Ef1169SourceKey,Rv9195Id,Ef1169DestKey" DisplayNameList="Ef1169Id" IsSeedTableSyncReq="false" DisplayFormatString="%1">#<ObjectMapping ObjectName="ExpandableFieldMaps" DatabaseName="spark" TableName="EXPANDABLE_FIELD_MAPS" PrimaryKey="Ef1169Id" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Ef1169Name,Rv9195Id,Ef1169SourceKey,Ef1169DestViewId,Ef1169DestKey" DisplayNameList="Ef1169Id" IsSeedTableSyncReq="false" DisplayFormatString="%1">#g' modified_schema.xml 

sed -i 's#<ObjectMapping ObjectName="AggregationTypesMaps" DatabaseName="spark" TableName="AGGREGATION_TYPES_MAPS" PrimaryKey="At2238Id" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Fc6138Id,Fc6138Id" DisplayNameList="At2238Id" IsSeedTableSyncReq="false" DisplayFormatString="%1">#<ObjectMapping ObjectName="AggregationTypesMaps" DatabaseName="spark" TableName="AGGREGATION_TYPES_MAPS" PrimaryKey="At2238Id" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Fc6138Id,At2238FieldCategoryId" DisplayNameList="At2238Id" IsSeedTableSyncReq="false" DisplayFormatString="%1">#g' modified_schema.xml

sed -i 's#<ObjectMapping ObjectName="FilterIndexFields" DatabaseName="spark" TableName="FILTER_INDEX_FIELDS" PrimaryKey="Rc4136IdFi9181FieldId" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Rc4136Id,Fi9181FieldId" DisplayNameList="Rc4136IdFi9181FieldId" IsSeedTableSyncReq="false" DisplayFormatString="%1">#<ObjectMapping ObjectName="FilterIndexFields" DatabaseName="spark" TableName="FILTER_INDEX_FIELDS" PrimaryKey="Rc4136Id,Fi9181FieldId" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Rc4136Id,Fi9181FieldId" DisplayNameList="Rc4136Id,Fi9181FieldId" IsSeedTableSyncReq="false" DisplayFormatString="%1">#g' modified_schema.xml

sed -i 's#<ObjectMapping ObjectName="FilterCaseInsensitiveFields" DatabaseName="spark" TableName="FILTER_CASE_INSENSITIVE_FIELDS" PrimaryKey="Rc4136IdFc0298DatabaseField" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Rc4136Id,Fc0298DatabaseField" DisplayNameList="Rc4136IdFc0298DatabaseField" IsSeedTableSyncReq="false" DisplayFormatString="%1">#<ObjectMapping ObjectName="FilterCaseInsensitiveFields" DatabaseName="spark" TableName="FILTER_CASE_INSENSITIVE_FIELDS" PrimaryKey="Rc4136Id,Fc0298DatabaseField" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Rc4136Id,Fc0298DatabaseField" DisplayNameList="Rc4136Id,Fc0298DatabaseField" IsSeedTableSyncReq="false" DisplayFormatString="%1">#g' modified_schema.xml

sed -i 's#<ObjectMapping ObjectName="PrecheckFieldConfigMap" DatabaseName="spark" TableName="PRECHECK_FIELD_CONFIG_MAP" PrimaryKey="Rc4136IdPf5189FieldId" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Rc4136Id,Pf5189FieldId" DisplayNameList="Rc4136IdPf5189FieldId" IsSeedTableSyncReq="false" DisplayFormatString="%1">#<ObjectMapping ObjectName="PrecheckFieldConfigMap" DatabaseName="spark" TableName="PRECHECK_FIELD_CONFIG_MAP" PrimaryKey="Rc4136Id,Pf5189FieldId" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Rc4136Id,Pf5189FieldId" DisplayNameList="Rc4136Id,Pf5189FieldId" IsSeedTableSyncReq="false" DisplayFormatString="%1">#g' modified_schema.xml

sed -i 's#<ObjectMapping ObjectName="Thresholds" DatabaseName="spark" TableName="THRESHOLDS" PrimaryKey="Th0128Id" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Tt5194Id,At7189Id,Ru575Key,Ru575Version" DisplayNameList="Th0128Id" IsSeedTableSyncReq="false" DisplayFormatString="%1">#<ObjectMapping ObjectName="Thresholds" DatabaseName="spark" TableName="THRESHOLDS" PrimaryKey="Th0128Id" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Tt5194Id,At7189Id,Th0128RuleKey,Th0128RuleVersion" DisplayNameList="Th0128Id" IsSeedTableSyncReq="false" DisplayFormatString="%1">#g' modified_schema.xml


sed -i 's#<ObjectMapping ObjectName="FpConfigurations" DatabaseName="spark" TableName="FP_CONFIGURATIONS" PrimaryKey="Fc7193Id" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Fe1123Id" DisplayNameList="Fc7193Id" IsSeedTableSyncReq="true" DisplayFormatString="%1">#<ObjectMapping ObjectName="FpConfigurations" DatabaseName="spark" TableName="FP_CONFIGURATIONS" PrimaryKey="Fc7193Id" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Fc6138Id" DisplayNameList="Fc7193Id" IsSeedTableSyncReq="true" DisplayFormatString="%1">#g' modified_schema.xml


sed -i 's#<ObjectMapping ObjectName="MlHmmInfo" DatabaseName="spark" TableName="ML_HMM_INFO" PrimaryKey="Mh659Id,Mh659Version,Mh1103Type,Mh1103State1,Mh1103State2" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Mh1103HmmId,Mh1103Version,Mh1103Type,Mh1103State1,Mh1103State2" DisplayNameList="Mh659Id,Mh659Version,Mh1103Type,Mh1103State1,Mh1103State2" IsSeedTableSyncReq="true" DisplayFormatString="%1">#<ObjectMapping ObjectName="MlHmmInfo" DatabaseName="spark" TableName="ML_HMM_INFO" PrimaryKey="Mh659Id,Mh659Version,Mh1103Type,Mh1103State1,Mh1103State2" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Mh659Id,Mh659Version,Mh1103Type,Mh1103State1,Mh1103State2" DisplayNameList="Mh659Id,Mh659Version,Mh1103Type,Mh1103State1,Mh1103State2" IsSeedTableSyncReq="true" DisplayFormatString="%1">#g' modified_schema.xml


sed -i 's#<ObjectMapping ObjectName="MlHmmInfoInt" DatabaseName="spark" TableName="ML_HMM_INFO_INT" PrimaryKey="Mh0102Id,Mh5146Type,Mh5146State1,Mh5146State2" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Mh5146HmmId,Mh5146Type,Mh5146State1,Mh5146State2" DisplayNameList="Mh0102Id,Mh5146Type,Mh5146State1,Mh5146State2" IsSeedTableSyncReq="true" DisplayFormatString="%1">#<ObjectMapping ObjectName="MlHmmInfoInt" DatabaseName="spark" TableName="ML_HMM_INFO_INT" PrimaryKey="Mh0102Id,Mh5146Type,Mh5146State1,Mh5146State2" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Mh0102Id,Mh5146Type,Mh5146State1,Mh5146State2" DisplayNameList="Mh0102Id,Mh5146Type,Mh5146State1,Mh5146State2" IsSeedTableSyncReq="true" DisplayFormatString="%1">#g' modified_schema.xml


sed -i 's#<ObjectMapping ObjectName="FeatureFpEntitiesMaps" DatabaseName="spark" TableName="FEATURE_FP_ENTITIES_MAPS" PrimaryKey="Ff4248Id" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Fc2247Id,Fe1123Id" DisplayNameList="Ff4248Id" IsSeedTableSyncReq="true" DisplayFormatString="%1">#<ObjectMapping ObjectName="FeatureFpEntitiesMaps" DatabaseName="spark" TableName="FEATURE_FP_ENTITIES_MAPS" PrimaryKey="Ff4248Id" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Fc2247Id, Fc6138Id" DisplayNameList="Ff4248Id" IsSeedTableSyncReq="true" DisplayFormatString="%1">#g' modified_schema.xml

sed -i 's#<ObjectMapping ObjectName="FeatureSchedulerMaps" DatabaseName="spark" TableName="FEATURE_SCHEDULER_MAPS" PrimaryKey="Fs2220Id" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Fs2220SchedulerJobName,Fc2247Id,Fs4176Id" DisplayNameList="Fs2220Id" IsSeedTableSyncReq="true" DisplayFormatString="%1">#<ObjectMapping ObjectName="FeatureSchedulerMaps" DatabaseName="spark" TableName="FEATURE_SCHEDULER_MAPS" PrimaryKey="Fs2220SchedulerJobName,Fc2247Id,Fs4176Id" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Fs2220SchedulerJobName,Fc2247Id,Fs4176Id" DisplayNameList="Fs2220Id" IsSeedTableSyncReq="true" DisplayFormatString="%1">#g' modified_schema.xml


sed -i 's#<ObjectMapping ObjectName="SchedulerParameters" DatabaseName="spark" TableName="SCHEDULER_PARAMETERS" PrimaryKey="Sp0211JobName," ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Sp0211JobName,Sp0211Parameter" DisplayNameList="Sp0211JobName," IsSeedTableSyncReq="true" DisplayFormatString="%1">#<ObjectMapping ObjectName="SchedulerParameters" DatabaseName="spark" TableName="SCHEDULER_PARAMETERS" PrimaryKey="Sp0211JobName,Sp0211Parameter" ServerPackageName="com.subex.nikira.database.hibernate.mappings.reference" ClientAssemblyName="Azure.Spark.Client.Objects" ClientNamespace="Azure.Spark.Client.Objects" MappingFileList="GUI/Server" BusinessConstraints="Sp0211JobName,Sp0211Parameter" DisplayNameList="Sp0211JobName,Sp0211Parameter" IsSeedTableSyncReq="true" DisplayFormatString="%1">#g#' modified_schema.xml
sed -i 's#A555_#UPD_#g' modified_schema.xml









