
spool test.log
set serveroutput on ;
set autotrace traceonly explain ;
SELECT NETWORK_ID, CALLER_NUMBER, CALLED_NUMBER, FORWARDED_NUMBER, RECORD_TYPE, DURATION, TIME_STAMP, EQUIPMENT_ID, IMSI_NUMBER, GEOGRAPHIC_POSITION, CALL_TYPE, SUBSCRIBER_ID, VAL, CDR_TYPE, SERVICE_TYPE, CDR_CATEGORY, IS_COMPLETE, IS_ATTEMPTED, SERVICE, PHONE_NUMBER, CDR_ID, DAY_OF_YEAR, HOUR_OF_DAY, OTHER_PARTY_COUNTRY_CODE, VPMN  FROM CDR_04 WHERE 1 = 1 AND  NETWORK_ID IN (1024,1025,1026,1027,1028) ORDER BY CDR_ID DESC ;
