sqlplus $DB_USER/$DB_PASSWORD << EOF
whenever sqlerror exit 5;
whenever oserror exit 5;


delete from ds_configuration where id like 'PROV94_TEST%';
insert into ds_configuration values ('PROV94_TEST.INPUT','$RANGERHOME/FMSData/DataSourcePROV94');
insert into ds_configuration values ('PROV94_TEST.OUTPUT','$RANGERHOME/FMSData/DataRecord/Process');
insert into ds_configuration values ('PROV94_TEST.REJECT','$RANGERHOME/FMSData/RejectedPROV94');
insert into ds_configuration values ('PROV94_TEST.LOG_FILE','prov94.log');
insert into ds_configuration values ('PROV94_TEST.REJECT.DATA','$RANGERHOME/FMSData/RejectedPROV94');
delete from output_format where datasource_name like 'PROV94_TEST%';
delete from datasource_info where datasource_name like '%PROV94_TEST%' ;
delete from parser where datasource_name like  'PROV94_TEST%'  ;
delete from ascii_delimited_field_info where parser_name = 'TESTPARSER'  ;

insert into datasource_info values('PROV94_TEST',2) ;
insert into output_format values ('PROV94_TEST',120,'|') ;
insert into parser values ('PROV94_TEST',1,'TESTPARSER') ;

INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',1,'SUBSCRIBER_IMSI') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',2,'SUBSCRIBER_SIM') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',3,'SUBSCRIBER_SIDBID') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',4,'SUBSCRIBER_CARRIER') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',5,'SUBSCRIBER_MARKET') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',6,'SUBSCRIBER_AGENT') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',7,'ACCOUNT_ACCOUNT_TYPE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',8,'SUBSCRIBER_RATE_PLAN') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',9,'SUBSCRIBER_CREDIT_LIMIT') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',10,'ACCOUNT_BILLING_DATE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',11,'SUBSCRIBER_SUBSCRIPTION_DATE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',12,'SUBSCRIBER_SUBSCRIPTION_STATUS') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',13,'SUBSCRIBER_STATUSTIME') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',14,'SUBSCRIBER_SPARE1') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',15,'SUBSCRIBER_SPARE2') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',16,'SUBSCRIBER_SPARE3') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',17,'SUBSCRIBER_SPARE4') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',18,'SUBSCRIBER_SPARE5') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',19,'SUBSCRIBER_NAME') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',20,'SUBSCRIBER_HOMEPHONENUMBER') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',21,'SUBSCRIBER_WORKPHONENUMBER') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',22,'SUBSCRIBER_ID_NUMBER') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',23,'SUBSCRIBER_SUBSCRIBER_SPARE6') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',24,'SUBSCRIBER_SUBSCRIBER_SPARE7') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',25,'ACCOUNT_BILLING_ID') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',26,'ACCOUNT_ACCOUNT_NAME') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',27,'ACCOUNT_CONTACT_NAME') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',28,'ACCOUNT_CONTACT_PHONE_NUMBER') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',29,'ACCOUNT_ADDRESS_LINE_1') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',30,'ACCOUNT_ADDRESS_LINE_2') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',31,'ACCOUNT_ADDRESS_LINE_3') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',32,'ACCOUNT_CITY') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',33,'ACCOUNT_REGION') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',34,'ACCOUNT_POST_CODE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',35,'ACCOUNT_COUNTRY') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',36,'ACCOUNT_START_DATE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',37,'ACCOUNT_SPARE1') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',38,'ACCOUNT_SPARE2') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',39,'ACCOUNT_SPARE3') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',40,'SUBSCRIBER_DIRECTORY_NUMBER') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',41,'ACCOUNT_MODE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',42,'SUBSCRIBER_HANDSET_ID') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',43,'ACCOUNT_CORPORATION') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',44,'ACCOUNT_COMPANY') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',45,'ACCOUNT_DIVISION') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',46,'ACCOUNT_MARKET') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',47,'ACCOUNT_MASTER_ID') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',48,'ACCOUNT_STATUS') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',49,'ACCOUNT_UPDATE_TIME') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',50,'ACCOUNT_CREDIT_CARD_TYPE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',51,'ACCOUNT_CREDIT_CARD_NUMBER') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',52,'ACCOUNT_ID') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',53,'ACCOUNT_ID_TYPE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',54,'ACCOUNT_ID_COUNTRY') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',55,'ACCOUNT_ID_PROVINCE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',56,'ACCOUNT_PAYMENT_TYPE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',57,'ACCOUNT_ACOUNT_SPARES') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',58,'ACCOUNT_CONTACT_TYPE1') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',59,'ACCOUNT_CONTACT1_HOME_PHONE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',60,'ACCOUNT_CONTACT2_TYPE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',61,'ACCOUNT_CONTACT2_NAME') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',62,'ACCOUNT_CONTACT2_WORK_PHONE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',63,'ACCOUNT_CONTACT2_HOME_PHONE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',64,'ACCOUNT_CONTACT2_ADDRESS_LINE1') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',65,'ACCOUNT_CONTACT2_ADDRESS_LINE2') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',66,'ACCOUNT_CONTACT2_ADDRESS_LINE3') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',67,'ACCOUNT_CONTACT2_CITY') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',68,'ACCOUNT_CONTACT2_REGION') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',69,'ACCOUNT_CONTACT2_POSTAL_CODE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',70,'ACCOUNT_CONTACT2_COUNTRY') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',71,'ACCOUNT_LIMIT_CHARGES') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',72,'SUBSCRIBER_CONTACT_TYPE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',73,'SUBSCRIBER_ADDRESS_LINE1') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',74,'SUBSCRIBER_ADDRESS_LINE2') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',75,'SUBSCRIBER_ADDRESS_LINE3') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',76,'SUBSCRIBER_ADDRESS_CITY') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',77,'SUBSCRIBER_REGION') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',78,'SUBSCRIBER_POST_CODE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',79,'SUBSCRIBER_COUNTRY') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',80,'SUBSCRIBER_ID_TYPE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',81,'SUBSCRIBER_ID_COUNTRY') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',82,'SUBSCRIBER_ID_PROVINCE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',83,'SUBSCRIBER_SUBSCRIPTION_SPARES') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',84,'ACCOUNT_DATE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',85,'ACCOUNT_NEW_CHARGES') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',86,'ACCOUNT_CURRENT_BALANCE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',87,'ACCOUNT_30_DAYS_BALANCE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',88,'ACCOUNT_60_DAYS_BALANCE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',89,'ACCOUNT_90_DAYS_BALANCE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',90,'ACCOUNT_PREVIOUS_BALANCE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',91,'ACCOUNT_LAST_PAYMENT') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',92,'ACCOUNT_LAST_PAYMENT_TYPE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',93,'ACCOUNT_LAST_PAYMENTCREDIT_CARD_TYPE') ;
INSERT INTO ASCII_DELIMITED_FIELD_INFO VALUES ('TESTPARSER',94,'ACCOUNT_LAST_PAYMENT_CREDIT_CARD_NUMBER') ;


delete from ascii_delimited_parser_info where parser_name = 'TESTPARSER'  ;
insert into ascii_delimited_parser_info values ('TESTPARSER',4096,'|','N','Y') ;

delete from validator where datasource_name = 'PROV94_TEST' ;
insert into validator values ('PROV94_TEST','SUBSCRIBER_IMSI',1,1,'') ;
insert into validator values ('PROV94_TEST','SUBSCRIBER_IMSI',2,2,'') ;

delete from formatter where datasource_name = 'PROV94_TEST' ;

insert into formatter values ('PROV94_TEST','SUBSCRIBER_SUBSCRIPTION_DATE',1,4,'PROV94_TEST_DATE') ;
delete from date_formatter where formatter_name like  'PROV94_TEST_DATE'  ;
delete from map_formatter where formatter_name like '%SUBS_MAP%' ;

insert into map_formatter values ('SUBS_MAP', '0', '0') ;
insert into map_formatter values ('SUBS_MAP', '1', '1') ;
insert into map_formatter values ('SUBS_MAP', '2', '2') ;
insert into map_formatter values ('SUBS_MAP', '5', '5') ;

insert into date_formatter values ('PROV94_TEST_DATE','%m/%d/%Y','%m/%d/%Y') ;
insert into formatter values ('PROV94_TEST','SUBSCRIBER_SUBSCRIPTION_STATUS', 1, 3, 'SUBS_MAP') ;


delete from rff_field_position_map where datasource_name = 'PROV94_TEST' ;
insert into rff_field_position_map values ('PROV94_TEST', 'SUBSCRIBER_SUBSCRIPTION_DATE', 1, '') ;
insert into rff_field_position_map values ('PROV94_TEST', 'SUBSCRIBER_IMSI', 38, '') ;
insert into rff_field_position_map values ('PROV94_TEST', 'ACCOUNT_LAST_PAYMENT_CREDIT_CARD_NUMBER', 120, '') ;

commit;
EOF

if test $? -eq 5
then
	exit 1
fi

exit 0

