mkdir -p  $RANGERHOME/FMSData/DataSourceMTX12LNP/
mkdir -p  $RANGERHOME/FMSData/DataSourceMTX12LNP/success/
mkdir -p  $RANGERHOME/FMSData/RejectedMTX12LNP/Data/

sqlplus $DB_USER/$DB_PASSWORD << EOF
whenever sqlerror exit 5;
whenever oserror exit 5;


DELETE FROM DATASOURCE_INFO WHERE DATASOURCE_NAME LIKE '%MTX12LNP_TEST%' ;
DELETE FROM PARSER WHERE PARSER_NAME LIKE '%MTX12LNP_PARSER%' ;

INSERT INTO DATASOURCE_INFO VALUES ('MTX12LNP_TEST',1) ;
INSERT INTO PARSER VALUES ('MTX12LNP_TEST',3,'MTX12LNP_PARSER') ;
INSERT INTO BDWRDW_BLOCK_CONFIGURATION VALUES ('MTX12LNP_PARSER','MTX_RECORD_BLOCK','C1C1',2048,10,0,2) ;
INSERT INTO BDWRDW_PARSER_CONFIGURATION VALUES ('MTX12LNP_PARSER','BLOCK_CODE_FIELD_SIZE',2) ;
INSERT INTO BDWRDW_RECORD_CONFIGURATION VALUES ('MTX_RECORD_BLOCK','CALL_DETAIL_RECORD','F7',290,'N') ;
INSERT INTO BDWRDW_FIELD_CONFIGURATION VALUES ('CALL_DETAIL_RECORD','CALLER_NUMBER',28,24) ;
INSERT INTO BDWRDW_FIELD_CONFIGURATION VALUES ('CALL_DETAIL_RECORD','ORIGINATION_TIME',312,9) ;

INSERT INTO RFF_FIELD_POSITION_MAP VALUES ('MTX12LNP_TEST', 'CALLER_NUMBER', 3, '') ;


commit ;

EOF

if test $? -eq 5
then
	exit 1
fi

exit 0
