#!/bin/bash

LOGFILE=$RANGERHOME/LOG/SingleViewBillingAuditLogsDML.log
TMPLOGFILE=billingauditlogdml.log

function RecreateBillingAuditLogsDML
{

	$SQL_COMMAND -s /nolog << EOF 
	connect $DB_USER/$DB_PASSWORD$DB_CONNECTION_STRING
	WHENEVER SQLERROR EXIT 5 ;
	SET FEEDBACK OFF ;
	SET SERVEROUTPUT OFF ;
	SET HEADING OFF;
	
	SPOOL $TMPLOGFILE

	UPDATE RECORD_CONFIGS SET TNAME='BILLING_AUDIT_LOGS', DESCRIPTION='Billing Audit Logs' WHERE ID=8003 ;
	UPDATE RECORD_VIEW_CONFIGS SET NAME='Billing Audit Logs' WHERE ID=8003 ;
	
	DELETE FROM FIELD_CONFIGS WHERE RECORD_CONFIG_ID=8003 ; 
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE,
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Network', 'NETWORK_ID',1 , 1, 1, 0, '', '', 20, 10, 1, 1, '', '') ;

	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE,
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION) 
		VALUES (field_configs_seq.nextval, 8003, 'User ID', 'USER_ID', 2, 2, 3, 0, '', '', 20, null, 1, 1, 10, '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION, FORMAT)  
		VALUES (field_configs_seq.nextval, 8003, 'Time Stamp', 'TIME_STAMP', 3, 3, 4, 0, '', '', 20, null, 1, 1, '', '', '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Account Number', 'ACCOUNT_NUMBER', 4, 4, 3, 1, '', '', 40, null, 1, 1, 10, '') ;
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Phone Number', 'PHONE_NUMBER', 5, 5, 3, 1, '', '', 40, null, 1, 1, 1, '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE,
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Subscriber ID', 'SUBSCRIBER_ID', 6, 6, 8, 0, '', '', 20, null, 0,0,'', '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Record Type','RECORD_TYPE', 7, 7, 1, 0, '', '', 16, 80013, 1, 1, '', '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Previous Value','PREVIOUS_VALUE', 8, 8, 3, 0, '', '', 128, null, 1, 1, 10, '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE,
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Current Value','CURRENT_VALUE', 9, 9, 3, 0, '', '', 128, null, 1, 0, 10, '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE,	IS_EXPANDABLE,
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION) 
		VALUES (field_configs_seq.nextval, 8003, 'Value Variation', 'VALUE_VARIATION', 10, 10, 2, 0, 
						'', '',  40, null, 1, 1, 9, '');
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE,
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES  (field_configs_seq.nextval, 8003, 'DS Name', 'DS_NAME', 11, 11, 3, 0, '', '',  256, null, 1, 1, 10, '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE,
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'File Name','FILE_NAME', 12, 12, 3, 0, '', '',  512, null, 1, 1, 10, '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Old Monthly Spend Limit in USD','OLD_MONTHLY_SPEND_LIMIT_IN_USD', 
				26, 13, 2, 0, '', '', 20, null, 1, 1, '', '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'New Monthly Spend Limit in USD','NEW_MONTHLY_SPEND_LIMIT_IN_USD', 
				27, 14, 2, 0, '', '', 20, null, 1, 1, '', '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION) 
		VALUES (field_configs_seq.nextval, 8003, 'IMEI', 'IMEI',23,15,3, 0,'', '',20, null,1, 0,'', '');
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION) 
		VALUES (field_configs_seq.nextval, 8003, 'IMSI', 'IMSI',24,16,3, 0,'', '',20, null,1, 0,'', '');
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION) 
		VALUES (field_configs_seq.nextval, 8003, 'Service', 'SERVICE',25,17,1, 0,'', '',20, null,1, 0,'', '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION) 
		VALUES (field_configs_seq.nextval, 8003, 'CDR Type', 'CDR_TYPE',22,18,1, 0,'', '',20, null,1, 0,'', '') ;

	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE,
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION, FORMAT)  
		VALUES (field_configs_seq.nextval, 8003, 'Receive Time', 'RECEIVE_TIME_ROCFM', 13, 19, 4, 0, 
				'GR CR', '', 20, null, 1, 1, '', '', '') ;

	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE,
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Optional Field 1','OPTIONAL_FIELD1', 16, 20, 3, 0, 
					'', '',  256, null, 0, 0, 10, '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Optional Field 2','OPTIONAL_FIELD2', 17, 21, 3, 0, 
					'', '',  256, null, 0, 0, 10, '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Optional Field 3','OPTIONAL_FIELD3', 18, 22, 3, 0, 
					'', '',  256, null, 0, 0, 10, '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Optional Field 4','OPTIONAL_FIELD4', 19, 23, 3, 0, 
					'', '',  256, null, 0, 0, 10, '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Optional Field 5','OPTIONAL_FIELD5', 20, 24, 3, 0, 
					'', '',  256, null, 0, 0, 10, '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Optional Field 6','OPTIONAL_FIELD6', 28, 25, 4, 0, 
					'', '',  20, null, 0, 0, '', '') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE, 
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'ID', 'ID', 21, 0, 8, 0, '', '', 20, null,0,0,null, '30') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE,
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Day Of Year', 'DAY_OF_YEAR', 14, 0, 8, 0, '', '', 20, null, 0,0,'', '1') ;
	
	INSERT INTO FIELD_CONFIGS (ID, RECORD_CONFIG_ID, NAME, DATABASE_FIELD, FIELD_ID, POSITION, DATA_TYPE, IS_EXPANDABLE,
		DS_CATEGORY, QUERY_FIELD, WIDTH, TRANSLATION_ID, IS_VISIBLE, IS_FILTER, REG_EXP_ID, DERIVATIVE_FUNCTION)  
		VALUES (field_configs_seq.nextval, 8003, 'Hour Of Day', 'HOUR_OF_DAY', 15, 0, 8, 0, '', '', 20, null, 0,0,'', '12') ;
	
	
	UPDATE TASKS SET NAME='Billing Audit Logs' WHERE NAME='TABS Audit Logs' ;
	UPDATE TASKS SET NAME='Billing Audit Logs Rule Creation' WHERE NAME='TABS Audit Logs Rule Creation' ;
	UPDATE TASKS SET NAME='Billing Audit Logs Template Creation' WHERE NAME='TABS Audit Logs Template Creation' ;
	  
	UPDATE COUNTER_DETAILS SET TABLE_NAME='BILLING_AUDIT_LOGS_COUNTER' WHERE ID=500 ;
	
	DELETE FROM CONFIGURATIONS WHERE CONFIG_KEY='CLEANUP.RECORDS.TABS_AUDIT_LOGS.OPTIONS' ;
	INSERT INTO CONFIGURATIONS (ID,CONFIG_KEY,VALUE,IS_VISIBLE) 
			VALUES (configurations_seq.nextval,'CLEANUP.RECORDS.BILLING_AUDIT_LOGS.OPTIONS','1970/01/01 00:00:00,30',0);
	
	DELETE FROM CONFIGURATIONS WHERE CONFIG_KEY='CLEANUP.RECORDS.TABS_AUDIT_LOGS.OPTIONS' ;
	INSERT INTO CONFIGURATIONS (ID,CONFIG_KEY,VALUE,IS_VISIBLE) 
			VALUES (configurations_seq.nextval,'BILLING_AUDIT_LOGSIDIncrement','1',0);
	
	DELETE FROM ARCHIVE_MAPS WHERE ARCHIVE_NAME='ARCHIVED_TABS_AUDIT_LOGS';
	INSERT INTO ARCHIVE_MAPS( ID,ARCHIVE_NAME,LOOKUP_TABLE_NAME,RECORD_CONFIG_ID) 
			VALUES(8003,'ARCHIVED_BILLING_AUDIT_LOGS','ARCHIVED_BILLING_AUDIT_LOGS',8003);
	
	DELETE FROM TAGS WHERE CATEGORY='TABS Audit Logs' ;
	INSERT INTO TAGS(SELECT tags_seq.nextval, DESCRIPTION, 'DATA_STREAMS' FROM RECORD_CONFIGS WHERE 
		IS_VISIBLE = 1 AND CATEGORY LIKE '%RULE_TAGS%' AND TNAME = 'BILLING_AUDIT_LOGS' ) ;
	
	DELETE FROM CONFIGURATIONS WHERE CONFIG_KEY='CLEANUP.RECORDS.TABS_AUDIT_LOGS.OPTIONS' ;
	INSERT INTO CONFIGURATIONS (ID,CONFIG_KEY,VALUE,IS_VISIBLE) 
			VALUES (configurations_seq.nextval,'BILLING_AUDIT_LOGSLOADER.KEY','999_9',0);
	
	DELETE FROM CONFIGURATIONS WHERE CONFIG_KEY='CLEANUP.RECORDS.TABS_AUDIT_LOGS.OPTIONS' ;
	INSERT INTO CONFIGURATIONS(ID, CONFIG_KEY, VALUE) VALUES (configurations_seq.nextval,
			'CLEANUP.RECORDS.ALARM_BILLING_AUDIT_LOGS.OPTIONS', '1970/01/01 00:00:00,90') ;
	
	DELETE FROM CONFIGURATIONS WHERE CONFIG_KEY='CLEANUP.RECORDS.TABS_AUDIT_LOGS.OPTIONS' ;
	INSERT INTO CONFIGURATIONS(ID, CONFIG_KEY, VALUE) VALUES (configurations_seq.nextval,
			'CLEANUP.RECORDS.LAST_ALARM_BILLING_AUDIT_LOGS_DAY_TRUNCED','');
	
	DELETE FROM ALARM_XDR_MAPS WHERE LOOKUP_TABLE_NAME='ALARM_TABS_AUDIT_LOGS' ;
	INSERT INTO ALARM_XDR_MAPS( ID,LOOKUP_TABLE_NAME,RECORD_CONFIG_ID) 
			VALUES(alarm_xdr_maps_seq.nextval,'ALARM_BILLING_AUDIT_LOGS',8003);
	
	DELETE FROM RTF_XDR_MAPS WHERE RECORD_CONFIG_ID=8003 ;
	INSERT INTO RTF_XDR_MAPS (RECORD_CONFIG_ID, RTF_TNAME, LOOKUP_TABLE_NAME) 
			VALUES (8003,'RTF_AR_BILLING_AUDIT_LOGS', 'RTF_ALARM_BILLING_AUDIT_LOGS') ;
	
	COMMIT ;
	SPOOL OFF ;
	QUIT ;

EOF
}


function main
{
	echo "Script started at `date` " >> $LOGFILE
	RecreateBillingAuditLogsDML
	cat $TMPLOGFILE >> $LOGFILE
	echo "Script finished at `date` " >> $LOGFILE
	rm $TMPLOGFILE
	echo "Check $LOGFILE for status." 
}	

main



